souffle: souffle::RamRelation Class Reference
souffle::RamRelation Class Reference
A RAM Relation in the RAM intermediate representation.
#include <RamRelation.h>
Public Member Functions
RamRelation * clone () const override
Create a clone (i.e.
const std::string getArg (uint32_t i) const
Get argument.
const std::string getArgTypeQualifier (uint32_t i) const
Get Argument Type Qualifier.
unsigned getArity () const
const std::vector< std::string > & getAttributeTypeQualifiers () const
const std::string & getName () const
Get name.
unsigned getNumberOfHeights () const
const RelationRepresentation getRepresentation () const
Relation representation type.
const bool isNullary () const
Is nullary relation.
const bool isTemp () const
Is temporary relation (for semi-naive evaluation)
bool operator< (const RamRelation &other) const
void print (std::ostream &out) const override
Print RAM node.
RamRelation (const std::string name, const size_t arity, const size_t numberOfHeights, const std::vector< std::string > attributeNames, const std::vector< std::string > attributeTypeQualifiers, const RelationRepresentation representation)
Public Member Functions inherited from souffle::RamNode
virtual void apply (const RamNodeMapper &mapper)
Apply the mapper to all child nodes.
virtual std::vector< const RamNode * > getChildNodes () const
Obtain list of all embedded child nodes.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, std::unique_ptr< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Data Fields
void * relation = nullptr
Used by Interpreter only.
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Attributes
const size_t arity
Arity, i.e., number of attributes.
const std::vector< std::string > attributeNames
Name of attributes.
const std::vector< std::string > attributeTypeQualifiers
Type of attributes.
const std::string name
Name of relation.
const size_t numberOfHeights
Number of height parameters for provenance.
const RelationRepresentation representation
Data-structure representation.
Detailed Description
A RAM Relation in the RAM intermediate representation.
Definition at line 39 of file RamRelation.h.
Constructor & Destructor Documentation
RamRelation()
souffle::RamRelation::RamRelation (const std::string name, const size_t arity, const size_t numberOfHeights, const std::vector< std::string > attributeNames, const std::vector< std::string > attributeTypeQualifiers, const RelationRepresentation representation) inline
Definition at line 63 of file RamRelation.h.
Referenced by clone().
             : name(std::move(name)), arity(arity), numberOfHeights(numberOfHeights),
               attributeNames(std::move(attributeNames)),
               attributeTypeQualifiers(std::move(attributeTypeQualifiers)), representation(representation) {
         assert(this->attributeNames.size() == arity || this->attributeNames.empty());
         assert(this->attributeTypeQualifiers.size() == arity || this->attributeTypeQualifiers.empty());
     }
Member Function Documentation
clone()
RamRelation* souffle::RamRelation::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamNode.
Definition at line 144 of file RamRelation.h.
References RamRelation().
Referenced by souffle::RamProgram::clone().
{
         return new RamRelation(
                 name, arity, numberOfHeights, attributeNames, attributeTypeQualifiers, representation);
     }
equal()
bool souffle::RamRelation::equal (const RamNode & other) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamNode.
Definition at line 150 of file RamRelation.h.
References isTemp(), and name.
{
         assert(nullptr != dynamic_cast<const RamRelation*>(&node));
         const auto& other = static_cast<const RamRelation&>(node);
         return name == other.name && arity == other.arity && attributeNames == other.attributeNames &&
                attributeTypeQualifiers == other.attributeTypeQualifiers &&
                representation == other.representation && isTemp() == other.isTemp();
     }
getArg()
const std::string souffle::RamRelation::getArg (uint32_t i) const inline
Get argument.
Definition at line 80 of file RamRelation.h.
References i.
Referenced by souffle::InterpreterProgInterface::InterpreterProgInterface(), print(), and souffle::RamIndexAnalysis::print().
{
         if (!attributeNames.empty()) {
             return attributeNames[i];
         }
         if (arity == 0) {
             return "";
         }
         return "c" + std::to_string(i);
     }
getArgTypeQualifier()
const std::string souffle::RamRelation::getArgTypeQualifier (uint32_t i) const inline
Get Argument Type Qualifier.
Definition at line 91 of file RamRelation.h.
Referenced by souffle::InterpreterProgInterface::InterpreterProgInterface().
{
         return (i < attributeTypeQualifiers.size()) ? attributeTypeQualifiers[i] : "";
     }
getArity()
unsigned souffle::RamRelation::getArity () const inline
Definition at line 115 of file RamRelation.h.
References arity.
Referenced by souffle::InterpreterEngine::execute(), souffle::Synthesiser::generateCode(), souffle::SynthesiserRelation::getArity(), souffle::RamIndexAnalysis::getSearchSignature(), souffle::SynthesiserRelation::getSynthesiserRelation(), souffle::InterpreterProgInterface::InterpreterProgInterface(), souffle::RamIndexAnalysis::print(), souffle::MakeIndexTransformer::rewriteAggregate(), souffle::MakeIndexTransformer::rewriteIndexScan(), and souffle::MakeIndexTransformer::rewriteScan().
{
         return arity;
     }
getAttributeTypeQualifiers()
const std::vector<std::string>& souffle::RamRelation::getAttributeTypeQualifiers () const inline
Definition at line 95 of file RamRelation.h.
References attributeTypeQualifiers.
Referenced by souffle::Synthesiser::emitCode(), and souffle::Synthesiser::generateCode().
{
         return attributeTypeQualifiers;
     }
getName()
const std::string& souffle::RamRelation::getName () const inline
Get name.
Definition at line 75 of file RamRelation.h.
References name.
Referenced by souffle::InterpreterEngine::execute(), souffle::InterpreterEngine::executeMain(), souffle::Synthesiser::generateCode(), souffle::Synthesiser::getRelationName(), souffle::InterpreterProgInterface::InterpreterProgInterface(), souffle::RamCreate::print(), souffle::RamLoad::print(), souffle::RamStore::print(), souffle::RamClear::print(), souffle::RamDrop::print(), souffle::RamIndexAnalysis::print(), souffle::RamIndexScan::print(), souffle::RamParallelIndexScan::print(), souffle::RamIndexChoice::print(), and souffle::RamParallelIndexChoice::print().
{
         return name;
     }
getNumberOfHeights()
unsigned souffle::RamRelation::getNumberOfHeights () const inline
Definition at line 120 of file RamRelation.h.
References numberOfHeights.
Referenced by souffle::SynthesiserDirectRelation::computeIndices(), souffle::Synthesiser::emitCode(), souffle::Synthesiser::generateCode(), souffle::SynthesiserDirectRelation::generateTypeStruct(), and souffle::RamIndexAnalysis::getSearchSignature().
{
         return numberOfHeights;
     }
getRepresentation()
const RelationRepresentation souffle::RamRelation::getRepresentation () const inline
Relation representation type.
Definition at line 105 of file RamRelation.h.
References representation.
Referenced by souffle::Synthesiser::emitCode(), souffle::SynthesiserRelation::getSynthesiserRelation(), and souffle::RamCreate::print().
{
         return representation;
     }
isNullary()
const bool souffle::RamRelation::isNullary () const inline
Is nullary relation.
Definition at line 100 of file RamRelation.h.
Referenced by souffle::SynthesiserRelation::getSynthesiserRelation().
{
         return arity == 0;
     }
isTemp()
const bool souffle::RamRelation::isTemp () const inline
Is temporary relation (for semi-naive evaluation)
Definition at line 110 of file RamRelation.h.
Referenced by souffle::Synthesiser::emitCode(), equal(), and souffle::Synthesiser::generateCode().
{
         return name.at(0) == '@';
     }
operator<()
bool souffle::RamRelation::operator< (const RamRelation & other) const inline
Definition at line 125 of file RamRelation.h.
References name.
{
         return name < other.name;
     }
print()
void souffle::RamRelation::print (std::ostream & out) const inline override virtual
Print RAM node.
Implements souffle::RamNode.
Definition at line 129 of file RamRelation.h.
References arity, getArg(), i, name, and representation.
{
         out << name;
         if (arity > 0) {
             out << "(" << getArg(0) << ":" << attributeTypeQualifiers[0];
             for (unsigned i = 1; i < arity; i++) {
                 out << ",";
                 out << getArg(i) << ":" << attributeTypeQualifiers[i];
             }
             out << ")";
             out << " " << representation;
         } else {
             out << " nullary";
         }
     }
Field Documentation
arity
const size_t souffle::RamRelation::arity protected
Arity, i.e., number of attributes.
Definition at line 45 of file RamRelation.h.
Referenced by getArity(), and print().
attributeNames
const std::vector<std::string> souffle::RamRelation::attributeNames protected
Name of attributes.
Definition at line 51 of file RamRelation.h.
attributeTypeQualifiers
const std::vector<std::string> souffle::RamRelation::attributeTypeQualifiers protected
Type of attributes.
Definition at line 54 of file RamRelation.h.
Referenced by getAttributeTypeQualifiers().
name
const std::string souffle::RamRelation::name protected
Name of relation.
Definition at line 42 of file RamRelation.h.
Referenced by equal(), getName(), operator<(), and print().
numberOfHeights
const size_t souffle::RamRelation::numberOfHeights protected
Number of height parameters for provenance.
Definition at line 48 of file RamRelation.h.
Referenced by getNumberOfHeights().
relation
void* souffle::RamRelation::relation = nullptr mutable
Used by Interpreter only.
Definition at line 61 of file RamRelation.h.
Referenced by souffle::RamRelationReference::clone(), souffle::RamRelationReference::equal(), souffle::RamRelationReference::get(), and souffle::RamRelationReference::print().
representation
const RelationRepresentation souffle::RamRelation::representation protected
Data-structure representation.
Definition at line 57 of file RamRelation.h.
Referenced by getRepresentation(), and print().
The documentation for this class was generated from the following file:
RamRelation.h