souffle: souffle::ExplainProvenance Class Reference
souffle::ExplainProvenance Class Reference abstract
#include <ExplainProvenance.h>
Public Member Functions
virtual std::unique_ptr< TreeNode > explain (std::string relName, std::vector< std::string > tuple, size_t depthLimit)=0
virtual std::unique_ptr< TreeNode > explainNegation (std::string relName, size_t ruleNum, const std::vector< std::string > &tuple, std::map< std::string, std::string > &bodyVariables)=0
virtual std::vector< std::string > explainNegationGetVariables (std::string relName, std::vector< std::string > args, size_t ruleNum)=0
ExplainProvenance (SouffleProgram &prog, bool useSublevels)
virtual std::unique_ptr< TreeNode > explainSubproof (std::string relName, RamDomain label, size_t depthLimit)=0
virtual std::string getRelationOutput (const std::string &relName)
virtual std::string getRule (std::string relName, size_t ruleNum)=0
virtual std::vector< std::string > getRules (std::string relName)=0
virtual std::string measureRelation (std::string relName)=0
virtual void printRulesJSON (std::ostream &os)=0
virtual void setup ()=0
virtual ~ExplainProvenance ()=default
Protected Member Functions
std::vector< RamDomain > argsToNums (const std::string &relName, const std::vector< std::string > &args) const
std::vector< std::string > numsToArgs (const std::string &relName, const std::vector< RamDomain > &nums, std::vector< bool > *err=nullptr) const
virtual void printRelationOutput (const std::vector< bool > &symMask, const IODirectives &ioDir, const Relation &rel)=0
Protected Attributes
SouffleProgram & prog
SymbolTable & symTable
bool useSublevels
Detailed Description
Definition at line 50 of file ExplainProvenance.h.
Constructor & Destructor Documentation
ExplainProvenance()
souffle::ExplainProvenance::ExplainProvenance (SouffleProgram & prog, bool useSublevels) inline
Definition at line 52 of file ExplainProvenance.h.
References explain(), explainNegation(), explainNegationGetVariables(), explainSubproof(), getRule(), getRules(), measureRelation(), printRulesJSON(), setup(), and ~ExplainProvenance().
             : prog(prog), symTable(prog.getSymbolTable()), useSublevels(useSublevels) {}
~ExplainProvenance()
virtual souffle::ExplainProvenance::~ExplainProvenance () virtual default
Referenced by ExplainProvenance().
Member Function Documentation
argsToNums()
std::vector<RamDomain> souffle::ExplainProvenance::argsToNums (const std::string & relName, const std::vector< std::string > & args) const inline protected
Definition at line 115 of file ExplainProvenance.h.
References souffle::SouffleProgram::getRelation(), i, and souffle::SymbolTable::lookup().
Referenced by souffle::ExplainProvenanceImpl::explain(), souffle::ExplainProvenanceImpl::explainNegation(), and souffle::ExplainProvenanceImpl::explainNegationGetVariables().
{
         std::vector<RamDomain> nums;
         auto rel = prog.getRelation(relName);
         if (rel == nullptr) {
             return nums;
         }
         for (size_t i = 0; i < args.size(); i++) {
             if (*rel->getAttrType(i) == 's') {
                 // remove quotation marks
                 if (args[i].size() >= 2 && args[i][0] == '"' && args[i][args[i].size() - 1] == '"') {
                     auto originalStr = args[i].substr(1, args[i].size() - 2);
                     nums.push_back(symTable.lookup(originalStr));
                 }
             } else {
                 nums.push_back(std::stoi(args[i]));
             }
         }
         return nums;
     }
explain()
virtual std::unique_ptr<TreeNode> souffle::ExplainProvenance::explain (std::string relName, std::vector< std::string > tuple, size_t depthLimit) pure virtual
Implemented in souffle::ExplainProvenanceImpl.
Referenced by ExplainProvenance(), and souffle::Explain::processCommand().
explainNegation()
virtual std::unique_ptr<TreeNode> souffle::ExplainProvenance::explainNegation (std::string relName, size_t ruleNum, const std::vector< std::string > & tuple, std::map< std::string, std::string > & bodyVariables) pure virtual
Implemented in souffle::ExplainProvenanceImpl.
Referenced by ExplainProvenance(), and souffle::Explain::processCommand().
explainNegationGetVariables()
virtual std::vector<std::string> souffle::ExplainProvenance::explainNegationGetVariables (std::string relName, std::vector< std::string > args, size_t ruleNum) pure virtual
Implemented in souffle::ExplainProvenanceImpl.
Referenced by ExplainProvenance(), and souffle::Explain::processCommand().
explainSubproof()
virtual std::unique_ptr<TreeNode> souffle::ExplainProvenance::explainSubproof (std::string relName, RamDomain label, size_t depthLimit) pure virtual
Implemented in souffle::ExplainProvenanceImpl.
Referenced by ExplainProvenance(), and souffle::Explain::processCommand().
getRelationOutput()
virtual std::string souffle::ExplainProvenance::getRelationOutput (const std::string & relName) inline virtual
Definition at line 78 of file ExplainProvenance.h.
References souffle::SouffleProgram::getRelation(), i, printRelationOutput(), prog, and souffle::IODirectives::setRelationName().
{
         auto rel = prog.getRelation(relName);
         if (rel == nullptr) {
             return "Relation " + relName + " not found\n";
         }
         // create symbol mask
         std::vector<bool> symMask(rel->getArity());
         for (size_t i = 0; i < rel->getArity(); i++) {
             if (*(rel->getAttrType(i)) == 's') {
                 symMask.at(i) = true;
             }
         }
         // create IODirectives
         IODirectives dir;
         dir.setRelationName(relName);
         // redirect cout to stringstream
         std::stringstream out;
         auto originalCoutBuf = std::cout.rdbuf(out.rdbuf());
         // print relation
         printRelationOutput(symMask, dir, *rel);
         // restore original cout buffer
         std::cout.rdbuf(originalCoutBuf);
         return out.str();
     }
getRule()
virtual std::string souffle::ExplainProvenance::getRule (std::string relName, size_t ruleNum) pure virtual
Implemented in souffle::ExplainProvenanceImpl.
Referenced by ExplainProvenance(), and souffle::Explain::processCommand().
getRules()
virtual std::vector<std::string> souffle::ExplainProvenance::getRules (std::string relName) pure virtual
Implemented in souffle::ExplainProvenanceImpl.
Referenced by ExplainProvenance(), and souffle::Explain::processCommand().
measureRelation()
virtual std::string souffle::ExplainProvenance::measureRelation (std::string relName) pure virtual
Implemented in souffle::ExplainProvenanceImpl.
Referenced by ExplainProvenance(), and souffle::Explain::processCommand().
numsToArgs()
std::vector<std::string> souffle::ExplainProvenance::numsToArgs (const std::string & relName, const std::vector< RamDomain > & nums, std::vector< bool > * err = nullptr) const inline protected
Definition at line 139 of file ExplainProvenance.h.
References err, souffle::SouffleProgram::getRelation(), i, printRelationOutput(), and souffle::SymbolTable::resolve().
Referenced by souffle::ExplainProvenanceImpl::explain(), and souffle::ExplainProvenanceImpl::explainNegation().
{
         std::vector<std::string> args;
         auto rel = prog.getRelation(relName);
         if (rel == nullptr) {
             return args;
         }
         for (size_t i = 0; i < nums.size(); i++) {
             if (err && (*err)[i]) {
                 args.push_back("_");
             } else {
                 if (*rel->getAttrType(i) == 's') {
                     args.push_back("\"" + std::string(symTable.resolve(nums[i])) + "\"");
                 } else {
                     args.push_back(std::to_string(nums[i]));
                 }
             }
         }
         return args;
     }
printRelationOutput()
virtual void souffle::ExplainProvenance::printRelationOutput (const std::vector< bool > & symMask, const IODirectives & ioDir, const Relation & rel) protected pure virtual
Implemented in souffle::ExplainProvenanceImpl.
Referenced by getRelationOutput(), and numsToArgs().
printRulesJSON()
virtual void souffle::ExplainProvenance::printRulesJSON (std::ostream & os) pure virtual
Implemented in souffle::ExplainProvenanceImpl.
Referenced by ExplainProvenance().
setup()
virtual void souffle::ExplainProvenance::setup () pure virtual
Implemented in souffle::ExplainProvenanceImpl.
Referenced by ExplainProvenance().
Field Documentation
prog
SouffleProgram& souffle::ExplainProvenance::prog protected
Definition at line 111 of file ExplainProvenance.h.
Referenced by souffle::ExplainProvenanceImpl::explain(), souffle::ExplainProvenanceImpl::explainNegation(), souffle::ExplainProvenanceImpl::explainSubproof(), souffle::ExplainProvenanceImpl::findTuple(), getRelationOutput(), souffle::ExplainProvenanceImpl::measureRelation(), souffle::ExplainProvenanceImpl::printRelationOutput(), and souffle::ExplainProvenanceImpl::setup().
symTable
SymbolTable& souffle::ExplainProvenance::symTable protected
Definition at line 112 of file ExplainProvenance.h.
Referenced by souffle::ExplainProvenanceImpl::explain(), souffle::ExplainProvenanceImpl::explainNegation(), souffle::ExplainProvenanceImpl::findTuple(), and souffle::ExplainProvenanceImpl::measureRelation().
useSublevels
bool souffle::ExplainProvenance::useSublevels protected
Definition at line 113 of file ExplainProvenance.h.
Referenced by souffle::ExplainProvenanceImpl::explain().
The documentation for this class was generated from the following file:
ExplainProvenance.h