souffle: souffle::AstFunctorDeclaration Class Reference
souffle::AstFunctorDeclaration Class Reference
AstFunctorDeclaration.
#include <AstFunctorDeclaration.h>
Public Member Functions
bool acceptsNumbers (size_t idx) const
accepts the i-th argument as a number value
bool acceptsSymbols (size_t idx) const
accepts the i-th argument as a symbolic value
void apply (const AstNodeMapper &) override
apply
AstFunctorDeclaration (const std::string &name, const std::string &type)
AstFunctorDeclaration * clone () const override
clone
size_t getArgCount () const
get number of arguments
std::vector< const AstNode * > getChildNodes () const override
get children
const std::string & getName () const
const std::string & getType () const
bool isNumerical () const
is return type a number value
bool isSymbolic () const
is return type a symbolic value
void print (std::ostream &out) const override
print
Public Member Functions inherited from souffle::AstNode
std::string extloc () const
Return source location of the syntactic element.
SrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (const SrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Abstract equality check for two AST nodes.
Private Attributes
const std::string name
name of functor
const std::string type
name of type
Detailed Description
AstFunctorDeclaration.
Definition at line 32 of file AstFunctorDeclaration.h.
Constructor & Destructor Documentation
AstFunctorDeclaration()
souffle::AstFunctorDeclaration::AstFunctorDeclaration (const std::string & name, const std::string & type) inline
Definition at line 41 of file AstFunctorDeclaration.h.
Referenced by clone().
                                                                         : name(name), type(type) {
         assert(name.length() > 0 && "functor name is empty");
         assert(type.length() > 0 && "type is empty");
     }
Member Function Documentation
acceptsNumbers()
bool souffle::AstFunctorDeclaration::acceptsNumbers (size_t idx) const inline
accepts the i-th argument as a number value
Definition at line 79 of file AstFunctorDeclaration.h.
References getArgCount().
Referenced by souffle::TypeAnalysis::analyseTypes(), and souffle::AstSemanticChecker::checkProgram().
{
         assert(idx <= getArgCount() && "argument index out of bound");
         return (type[idx] == 'N');
     }
acceptsSymbols()
bool souffle::AstFunctorDeclaration::acceptsSymbols (size_t idx) const inline
accepts the i-th argument as a symbolic value
Definition at line 73 of file AstFunctorDeclaration.h.
References getArgCount().
Referenced by souffle::TypeAnalysis::analyseTypes(), and souffle::AstSemanticChecker::checkProgram().
{
         assert(idx <= getArgCount() && "argument index out of bound");
         return (type[idx] == 'S');
     }
apply()
void souffle::AstFunctorDeclaration::apply (const AstNodeMapper &) inline override virtual
apply
Implements souffle::AstNode.
Definition at line 112 of file AstFunctorDeclaration.h.
{
         // nothing to do
     }
clone()
AstFunctorDeclaration* souffle::AstFunctorDeclaration::clone () const inline override virtual
clone
Implements souffle::AstNode.
Definition at line 117 of file AstFunctorDeclaration.h.
References AstFunctorDeclaration(), and souffle::AstNode::getSrcLoc().
{
         auto* res = new AstFunctorDeclaration(name, type);
         res->setSrcLoc(getSrcLoc());
         return res;
     }
equal()
bool souffle::AstFunctorDeclaration::equal (const AstNode & other) const inline override protected virtual
Abstract equality check for two AST nodes.
Implements souffle::AstNode.
Definition at line 124 of file AstFunctorDeclaration.h.
References name.
{
         assert(nullptr != dynamic_cast<const AstFunctorDeclaration*>(&node));
         const auto& other = static_cast<const AstFunctorDeclaration&>(node);
         return name == other.name && type == other.type;
     }
getArgCount()
size_t souffle::AstFunctorDeclaration::getArgCount () const inline
get number of arguments
Definition at line 55 of file AstFunctorDeclaration.h.
Referenced by acceptsNumbers(), acceptsSymbols(), and souffle::AstSemanticChecker::checkProgram().
{
         assert(type.length() > 0 && "wrong type declaration for user-defined functor");
         return type.length() - 1;
     }
getChildNodes()
std::vector<const AstNode*> souffle::AstFunctorDeclaration::getChildNodes () const inline override virtual
get children
Implements souffle::AstNode.
Definition at line 106 of file AstFunctorDeclaration.h.
{
         std::vector<const AstNode*> res;
         return res;  // no child nodes
     }
getName()
const std::string& souffle::AstFunctorDeclaration::getName () const inline
Definition at line 46 of file AstFunctorDeclaration.h.
References name.
{
         return name;
     }
getType()
const std::string& souffle::AstFunctorDeclaration::getType () const inline
Definition at line 50 of file AstFunctorDeclaration.h.
References type.
Referenced by souffle::AstTranslator::translateValue().
{
         return type;
     }
isNumerical()
bool souffle::AstFunctorDeclaration::isNumerical () const inline
is return type a number value
Definition at line 67 of file AstFunctorDeclaration.h.
Referenced by souffle::TypeAnalysis::analyseTypes(), and souffle::AstSemanticChecker::checkProgram().
{
         assert(type.length() > 0 && "wrong type declaration for user-defined functor");
         return (type[type.length() - 1] == 'N');
     }
isSymbolic()
bool souffle::AstFunctorDeclaration::isSymbolic () const inline
is return type a symbolic value
Definition at line 61 of file AstFunctorDeclaration.h.
Referenced by souffle::TypeAnalysis::analyseTypes(), and souffle::AstSemanticChecker::checkProgram().
{
         assert(type.length() > 0 && "wrong type declaration for user-defined functor");
         return (type[type.length() - 1] == 'S');
     }
print()
void souffle::AstFunctorDeclaration::print (std::ostream & out) const inline override virtual
print
Implements souffle::AstNode.
Definition at line 85 of file AstFunctorDeclaration.h.
References i, souffle::join(), and type.
{
         auto convert = [&](char type) {
             switch (type) {
                 case 'N':
                     return "number";
                 case 'S':
                     return "symbol";
                 default:
                     abort();
             }
         };
         out << ".declfun " << name << "(";
         std::vector<std::string> args;
         for (size_t i = 0; i < type.length() - 1; i++) {
             args.push_back(convert(type[i]));
         }
         out << join(args, ",");
         out << "):" << convert(type[type.length() - 1]) << std::endl;
     }
Field Documentation
name
const std::string souffle::AstFunctorDeclaration::name private
name of functor
Definition at line 35 of file AstFunctorDeclaration.h.
Referenced by equal(), and getName().
type
const std::string souffle::AstFunctorDeclaration::type private
name of type
Definition at line 38 of file AstFunctorDeclaration.h.
Referenced by getType(), and print().
The documentation for this class was generated from the following file:
AstFunctorDeclaration.h