souffle: souffle::RelationWrapper< id, RelType, TupleType, Arity, NumberOfHeights > Class Template Reference
souffle::RelationWrapper< id, RelType, TupleType, Arity, NumberOfHeights > Class Template Reference
Relation wrapper used internally in the generated Datalog program.
#include <CompiledSouffle.h>
Data Structures
class iterator_wrapper
Public Member Functions
iterator begin () const override
Return an iterator pointing to the first tuple of the relation.
bool contains (const tuple &arg) const override
Check whether a tuple exists in a relation.
iterator end () const override
Return an iterator pointing to next to the last tuple of the relation.
size_t getArity () const override
Get the arity of a relation.
const char * getAttrName (size_t arg) const override
Get the attribute name of a relation at the column specified by the parameter.
const char * getAttrType (size_t arg) const override
Get the attribute type of a relation at the column specified by the parameter.
std::string getName () const override
Get the name of a relation.
size_t getNumberOfHeights () const override
SymbolTable & getSymbolTable () const override
Get the symbol table of a relation.
void insert (const tuple &arg) override
Insert a new tuple into the relation.
void purge () override
Eliminate all the tuples in relation.
RelationWrapper (RelType &r, SymbolTable &s, std::string name, const std::array< const char *, Arity > &t, const std::array< const char *, Arity > &n)
std::size_t size () const override
Get the number of tuples in a relation.
Public Member Functions inherited from souffle::Relation
std::string getSignature ()
Get the signature of a relation.
virtual ~Relation ()=default
Destructor.
Private Attributes
std::string name
RelType & relation
SymbolTable & symTable
std::array< const char *, Arity > tupleName
std::array< const char *, Arity > tupleType
Detailed Description
template<uint32_t id, class RelType, class TupleType, size_t Arity, size_t NumberOfHeights>
class souffle::RelationWrapper< id, RelType, TupleType, Arity, NumberOfHeights >
Relation wrapper used internally in the generated Datalog program.
Definition at line 66 of file CompiledSouffle.h.
Constructor & Destructor Documentation
RelationWrapper()
template<uint32_t id, class RelType , class TupleType , size_t Arity, size_t NumberOfHeights> souffle::RelationWrapper< id, RelType, TupleType, Arity, NumberOfHeights >::RelationWrapper (RelType & r, SymbolTable & s, std::string name, const std::array< const char *, Arity > & t, const std::array< const char *, Arity > & n) inline
Definition at line 104 of file CompiledSouffle.h.
             : relation(r), symTable(s), name(std::move(name)), tupleType(t), tupleName(n) {}
Member Function Documentation
begin()
template<uint32_t id, class RelType , class TupleType , size_t Arity, size_t NumberOfHeights> iterator souffle::RelationWrapper< id, RelType, TupleType, Arity, NumberOfHeights >::begin () const inline override virtual
Return an iterator pointing to the first tuple of the relation.
This iterator is used to access the tuples of the relation.
Returns
Iterator
Implements souffle::Relation.
Definition at line 107 of file CompiledSouffle.h.
References souffle::RelationWrapper< id, RelType, TupleType, Arity, NumberOfHeights >::iterator_wrapper::iterator_wrapper().
{
         return iterator(new iterator_wrapper(id, this, relation.begin()));
     }
contains()
template<uint32_t id, class RelType , class TupleType , size_t Arity, size_t NumberOfHeights> bool souffle::RelationWrapper< id, RelType, TupleType, Arity, NumberOfHeights >::contains (const tuple & t) const inline override virtual
Check whether a tuple exists in a relation.
The definition of contains has to be defined by the child class of relation class.
Parameters
t Reference to a tuple object
Returns
Boolean. True, if the tuple exists. False, otherwise
Implements souffle::Relation.
Definition at line 122 of file CompiledSouffle.h.
References i, souffle::tuple::size(), and souffle::RelationWrapper< id, RelType, TupleType, Arity, NumberOfHeights >::iterator_wrapper::t.
{
         TupleType t;
         assert(arg.size() == Arity && "wrong tuple arity");
         for (size_t i = 0; i < Arity; i++) {
             t[i] = arg[i];
         }
         return relation.contains(t);
     }
end()
template<uint32_t id, class RelType , class TupleType , size_t Arity, size_t NumberOfHeights> iterator souffle::RelationWrapper< id, RelType, TupleType, Arity, NumberOfHeights >::end () const inline override virtual
Return an iterator pointing to next to the last tuple of the relation.
Returns
Iterator
Implements souffle::Relation.
Definition at line 110 of file CompiledSouffle.h.
References souffle::RelationWrapper< id, RelType, TupleType, Arity, NumberOfHeights >::iterator_wrapper::iterator_wrapper().
{
         return iterator(new iterator_wrapper(id, this, relation.end()));
     }
getArity()
template<uint32_t id, class RelType , class TupleType , size_t Arity, size_t NumberOfHeights> size_t souffle::RelationWrapper< id, RelType, TupleType, Arity, NumberOfHeights >::getArity () const inline override virtual
Get the arity of a relation.
For example for a tuple (1 2) the arity is 2 and for a tuple (1 2 3) the arity is 3.
Returns
Arity of a relation (size_t)
Implements souffle::Relation.
Definition at line 144 of file CompiledSouffle.h.
{
         return Arity;
     }
getAttrName()
template<uint32_t id, class RelType , class TupleType , size_t Arity, size_t NumberOfHeights> const char* souffle::RelationWrapper< id, RelType, TupleType, Arity, NumberOfHeights >::getAttrName (size_t) const inline override virtual
Get the attribute name of a relation at the column specified by the parameter.
The attribute name is the name given to the type by the user in the .decl statement. For example, for ".decl edge (node1:Node, node2:Node)", the attribute names are node1 and node2.
Parameters
The index of the column starting starting from 0 (size_t)
Returns
The constant string of the attribute name
Implements souffle::Relation.
Definition at line 140 of file CompiledSouffle.h.
{
         assert(false <= arg && arg < Arity && "attribute out of bound");
         return tupleName[arg];
     }
getAttrType()
template<uint32_t id, class RelType , class TupleType , size_t Arity, size_t NumberOfHeights> const char* souffle::RelationWrapper< id, RelType, TupleType, Arity, NumberOfHeights >::getAttrType (size_t) const inline override virtual
Get the attribute type of a relation at the column specified by the parameter.
The attribute type is in the form "<primitive type>:<type name>". <primitive type>=""> can be s or n standing for symbol or number which are two primitive types in Souffle. <type name>=""> is the name given by the user in the Souffle Program after ".type", "symbol_type" or "number_type". For example, for ".type Node", the type name is "Node".
Parameters
The index of the column starting starting from 0 (size_t)
Returns
The constant string of the attribute type
Implements souffle::Relation.
Definition at line 136 of file CompiledSouffle.h.
{
         assert(false <= arg && arg < Arity && "attribute out of bound");
         return tupleType[arg];
     }
getName()
template<uint32_t id, class RelType , class TupleType , size_t Arity, size_t NumberOfHeights> std::string souffle::RelationWrapper< id, RelType, TupleType, Arity, NumberOfHeights >::getName () const inline override virtual
Get the name of a relation.
Returns
The name of a relation (std::string)
Implements souffle::Relation.
Definition at line 133 of file CompiledSouffle.h.
References souffle::RelationWrapper< id, RelType, TupleType, Arity, NumberOfHeights >::name.
{
         return name;
     }
getNumberOfHeights()
template<uint32_t id, class RelType , class TupleType , size_t Arity, size_t NumberOfHeights> size_t souffle::RelationWrapper< id, RelType, TupleType, Arity, NumberOfHeights >::getNumberOfHeights () const inline override virtual
Implements souffle::Relation.
Definition at line 147 of file CompiledSouffle.h.
{
         return NumberOfHeights;
     }
getSymbolTable()
template<uint32_t id, class RelType , class TupleType , size_t Arity, size_t NumberOfHeights> SymbolTable& souffle::RelationWrapper< id, RelType, TupleType, Arity, NumberOfHeights >::getSymbolTable () const inline override virtual
Get the symbol table of a relation.
The symbols in a tuple to be stored into a relation are stored and assigned with a number in a table called symbol table. For example, to insert ("John","Student") to a relation, "John" and "Student" are stored in symbol table and they are assigned with number say 0 and 1. After this, instead of inserting ("John","Student"), (0, 1) is inserted. When accessing this tuple, 0 and 1 will be looked up in the table and replaced by "John" and "Student". This is done so to save memory space if same symbols are inserted many times. Symbol table has many rows where each row contains a symbol and its corresponding assigned number.
Returns
Reference to a symbolTable object
Implements souffle::Relation.
Definition at line 150 of file CompiledSouffle.h.
References souffle::RelationWrapper< id, RelType, TupleType, Arity, NumberOfHeights >::symTable.
{
         return symTable;
     }
insert()
template<uint32_t id, class RelType , class TupleType , size_t Arity, size_t NumberOfHeights> void souffle::RelationWrapper< id, RelType, TupleType, Arity, NumberOfHeights >::insert (const tuple & t) inline override virtual
Insert a new tuple into the relation.
The definition of insert function has to be defined by the child class of relation class.
Parameters
t Reference to a tuple class object
Implements souffle::Relation.
Definition at line 113 of file CompiledSouffle.h.
References souffle::tuple::getRelation(), i, souffle::tuple::size(), and souffle::RelationWrapper< id, RelType, TupleType, Arity, NumberOfHeights >::iterator_wrapper::t.
Referenced by souffle::t_nullaries::insertAll().
{
         TupleType t;
         assert(&arg.getRelation() == this && "wrong relation");
         assert(arg.size() == Arity && "wrong tuple arity");
         for (size_t i = 0; i < Arity; i++) {
             t[i] = arg[i];
         }
         relation.insert(t);
     }
purge()
template<uint32_t id, class RelType , class TupleType , size_t Arity, size_t NumberOfHeights> void souffle::RelationWrapper< id, RelType, TupleType, Arity, NumberOfHeights >::purge () inline override virtual
Eliminate all the tuples in relation.
Implements souffle::Relation.
Definition at line 155 of file CompiledSouffle.h.
{
         relation.purge();
     }
size()
template<uint32_t id, class RelType , class TupleType , size_t Arity, size_t NumberOfHeights> std::size_t souffle::RelationWrapper< id, RelType, TupleType, Arity, NumberOfHeights >::size () const inline override virtual
Get the number of tuples in a relation.
Returns
The number of tuples in a relation (std::size_t)
Implements souffle::Relation.
Definition at line 130 of file CompiledSouffle.h.
{
         return relation.size();
     }
Field Documentation
name
template<uint32_t id, class RelType , class TupleType , size_t Arity, size_t NumberOfHeights> std::string souffle::RelationWrapper< id, RelType, TupleType, Arity, NumberOfHeights >::name private
Definition at line 70 of file CompiledSouffle.h.
Referenced by souffle::RelationWrapper< id, RelType, TupleType, Arity, NumberOfHeights >::getName().
relation
template<uint32_t id, class RelType , class TupleType , size_t Arity, size_t NumberOfHeights> RelType& souffle::RelationWrapper< id, RelType, TupleType, Arity, NumberOfHeights >::relation private
Definition at line 68 of file CompiledSouffle.h.
symTable
template<uint32_t id, class RelType , class TupleType , size_t Arity, size_t NumberOfHeights> SymbolTable& souffle::RelationWrapper< id, RelType, TupleType, Arity, NumberOfHeights >::symTable private
Definition at line 69 of file CompiledSouffle.h.
Referenced by souffle::RelationWrapper< id, RelType, TupleType, Arity, NumberOfHeights >::getSymbolTable().
tupleName
template<uint32_t id, class RelType , class TupleType , size_t Arity, size_t NumberOfHeights> std::array<const char*, Arity> souffle::RelationWrapper< id, RelType, TupleType, Arity, NumberOfHeights >::tupleName private
Definition at line 72 of file CompiledSouffle.h.
tupleType
template<uint32_t id, class RelType , class TupleType , size_t Arity, size_t NumberOfHeights> std::array<const char*, Arity> souffle::RelationWrapper< id, RelType, TupleType, Arity, NumberOfHeights >::tupleType private
Definition at line 71 of file CompiledSouffle.h.
The documentation for this class was generated from the following file:
CompiledSouffle.h