souffle: souffle::AstRelation Class Reference
souffle::AstRelation Class Reference
#include <AstRelation.h>
Public Member Functions
void addAttribute (std::unique_ptr< AstAttribute > attr)
Add a new used type to this relation.
void addClause (std::unique_ptr< AstClause > clause)
Add a clause to the relation.
void addLoad (std::unique_ptr< AstLoad > directive)
void addStore (std::unique_ptr< AstStore > directive)
void apply (const AstNodeMapper &map) override
Mutates this node.
AstRelation ()=default
size_t clauseSize () const
Return the number of clauses associated with this relation.
AstRelation * clone () const override
Creates a clone of this AST sub-structure.
size_t getArity () const
Return the arity of this relation.
AstAttribute * getAttribute (size_t idx) const
Return the declared type at position idx.
std::vector< AstAttribute * > getAttributes () const
Obtains a list of the contained attributes.
std::vector< const AstNode * > getChildNodes () const override
Obtains a list of all embedded child nodes.
AstClause * getClause (size_t idx) const
Return i-th clause associated with this relation.
std::vector< AstClause * > getClauses () const
Obtains a list of the associated clauses.
std::vector< AstLoad * > getLoads () const
const AstRelationIdentifier & getName () const
Return the name of the relation.
int getQualifier () const
Return qualifier associated with this relation.
RelationRepresentation getRepresentation () const
Get representation for this relation.
std::vector< AstStore * > getStores () const
bool hasRecordInHead () const
Check whether relation has a record in its head.
bool isInline () const
Check whether relation is an inlined relation.
bool isOverridable () const
Check whether relation is an overridable relation.
bool isSuppressed () const
Check whether relation warnings are suppressed.
size_t numberOfHeightParameters () const
Get number of height parameters.
void print (std::ostream &os) const override
Print string representation of the relation to a given output stream.
bool removeClause (const AstClause *clause)
Removes the given clause from this relation.
void setName (const AstRelationIdentifier &n)
Set name for this relation.
void setQualifier (int q)
Set qualifier associated with this relation.
void setRepresentation (RelationRepresentation representation)
~AstRelation () override=default
Public Member Functions inherited from souffle::AstNode
std::string extloc () const
Return source location of the syntactic element.
SrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (const SrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Implements the node comparison for this node type.
Protected Attributes
std::vector< std::unique_ptr< AstAttribute > > attributes
Attributes of the relation.
std::vector< std::unique_ptr< AstClause > > clauses
Clauses associated with this relation.
std::vector< std::unique_ptr< AstLoad > > loads
AstRelationIdentifier name
Name of relation.
int qualifier = 0
Qualifier of relation (i.e., output or not an output relation)
RelationRepresentation representation {RelationRepresentation::DEFAULT}
Datastructure to use for this relation.
std::vector< std::unique_ptr< AstStore > > stores
IO directives associated with this relation.
Friends
std::ostream & operator<< (std::ostream &os, const AstRelation &rel)
Operator overload, calls print if reference is given.
std::ostream & operator<< (std::ostream &os, const AstRelation *rel)
Operator overload, prints name if pointer is given.
Detailed Description
Definition at line 76 of file AstRelation.h.
Constructor & Destructor Documentation
AstRelation()
souffle::AstRelation::AstRelation () default
Referenced by clone().
~AstRelation()
souffle::AstRelation::~AstRelation () override default
Member Function Documentation
addAttribute()
void souffle::AstRelation::addAttribute (std::unique_ptr< AstAttribute > attr) inline
Add a new used type to this relation.
Definition at line 93 of file AstRelation.h.
References attributes.
Referenced by souffle::MagicSetTransformer::transform().
{
         assert(attr && "Undefined attribute");
         attributes.push_back(std::move(attr));
     }
addClause()
void souffle::AstRelation::addClause (std::unique_ptr< AstClause > clause) inline
Add a clause to the relation.
Definition at line 276 of file AstRelation.h.
References clauses, and name.
Referenced by souffle::MagicSetTransformer::transform(), and souffle::transformEqrelRelation().
{
         assert(clause && "Undefined clause");
         assert(clause->getHead() && "Undefined head of the clause");
         assert(clause->getHead()->getName() == name &&
                 "Name of the atom in the head of the clause and the relation do not match");
         clauses.push_back(std::move(clause));
     }
addLoad()
void souffle::AstRelation::addLoad (std::unique_ptr< AstLoad > directive) inline
Definition at line 323 of file AstRelation.h.
References loads.
Referenced by souffle::MagicSetTransformer::transform().
{
         assert(directive && "Undefined directive");
         loads.push_back(std::move(directive));
     }
addStore()
void souffle::AstRelation::addStore (std::unique_ptr< AstStore > directive) inline
Definition at line 318 of file AstRelation.h.
References stores.
Referenced by souffle::MagicSetTransformer::transform().
{
         assert(directive && "Undefined directive");
         stores.push_back(std::move(directive));
     }
apply()
void souffle::AstRelation::apply (const AstNodeMapper & map) inline override virtual
Mutates this node.
Implements souffle::AstNode.
Definition at line 250 of file AstRelation.h.
References attributes, clauses, loads, and stores.
{
         for (auto& cur : attributes) {
             cur = map(std::move(cur));
         }
         for (auto& cur : clauses) {
             cur = map(std::move(cur));
         }
         for (auto& cur : stores) {
             cur = map(std::move(cur));
         }
         for (auto& cur : loads) {
             cur = map(std::move(cur));
         }
     }
clauseSize()
size_t souffle::AstRelation::clauseSize () const inline
Return the number of clauses associated with this relation.
Definition at line 296 of file AstRelation.h.
References clauses.
Referenced by souffle::AstSemanticChecker::checkRelation().
{
         return clauses.size();
     }
clone()
AstRelation* souffle::AstRelation::clone () const inline override virtual
Creates a clone of this AST sub-structure.
Implements souffle::AstNode.
Definition at line 229 of file AstRelation.h.
References AstRelation(), attributes, clauses, souffle::AstNode::getSrcLoc(), loads, name, qualifier, and stores.
{
         auto res = new AstRelation();
         res->name = name;
         res->setSrcLoc(getSrcLoc());
         for (const auto& cur : attributes) {
             res->attributes.emplace_back(cur->clone());
         }
         for (const auto& cur : clauses) {
             res->clauses.emplace_back(cur->clone());
         }
         for (const auto& cur : stores) {
             res->stores.emplace_back(cur->clone());
         }
         for (const auto& cur : loads) {
             res->loads.emplace_back(cur->clone());
         }
         res->qualifier = qualifier;
         return res;
     }
equal()
bool souffle::AstRelation::equal (const AstNode & node) const inline override protected virtual
Implements the node comparison for this node type.
Implements souffle::AstNode.
Definition at line 359 of file AstRelation.h.
References souffle::equal_targets().
{
         assert(nullptr != dynamic_cast<const AstRelation*>(&node));
         const auto& other = static_cast<const AstRelation&>(node);
         return name == other.name && equal_targets(attributes, other.attributes) &&
                equal_targets(clauses, other.clauses);
     }
getArity()
size_t souffle::AstRelation::getArity () const inline
Return the arity of this relation.
Definition at line 99 of file AstRelation.h.
References attributes.
Referenced by souffle::AstSemanticChecker::checkRelation(), souffle::AstSemanticChecker::checkRelationDeclaration(), souffle::createMagicRelation(), souffle::AstTranslator::getOutputIODirectives(), souffle::Adornment::run(), souffle::MagicSetTransformer::transform(), souffle::transformEqrelRelation(), and souffle::AstTranslator::translateRelation().
{
         return attributes.size();
     }
getAttribute()
AstAttribute* souffle::AstRelation::getAttribute (size_t idx) const inline
Return the declared type at position idx.
Definition at line 104 of file AstRelation.h.
References attributes.
Referenced by souffle::AstSemanticChecker::checkRelation(), souffle::AstSemanticChecker::checkRelationDeclaration(), souffle::AstTranslator::getOutputIODirectives(), and souffle::AstTranslator::translateRelation().
{
         return attributes[idx].get();
     }
getAttributes()
std::vector<AstAttribute*> souffle::AstRelation::getAttributes () const inline
Obtains a list of the contained attributes.
Definition at line 109 of file AstRelation.h.
References attributes, and souffle::toPtrVector().
Referenced by souffle::createMagicRelation(), souffle::createNewRelation(), souffle::MagicSetTransformer::transform(), souffle::BddBddBTranslator::visitRelation(), and souffle::LogicbloxConverter::visitRelation().
{
         return toPtrVector(attributes);
     }
getChildNodes()
std::vector<const AstNode*> souffle::AstRelation::getChildNodes () const inline override virtual
Obtains a list of all embedded child nodes.
Implements souffle::AstNode.
Definition at line 301 of file AstRelation.h.
References attributes, clauses, loads, and stores.
{
         std::vector<const AstNode*> res;
         for (const auto& cur : attributes) {
             res.push_back(cur.get());
         }
         for (const auto& cur : clauses) {
             res.push_back(cur.get());
         }
         for (const auto& cur : stores) {
             res.push_back(cur.get());
         }
         for (const auto& cur : loads) {
             res.push_back(cur.get());
         }
         return res;
     }
getClause()
AstClause* souffle::AstRelation::getClause (size_t idx) const inline
Return i-th clause associated with this relation.
Definition at line 266 of file AstRelation.h.
References clauses.
{
         return clauses[idx].get();
     }
getClauses()
std::vector<AstClause*> souffle::AstRelation::getClauses () const inline
Obtains a list of the associated clauses.
Definition at line 271 of file AstRelation.h.
References clauses, and souffle::toPtrVector().
Referenced by souffle::addForwardDependencies(), souffle::AstSemanticChecker::checkRelation(), souffle::RecursiveClauses::computeIsRecursive(), souffle::getInlinedLiteral(), souffle::hasClauseWithAggregatedRelation(), souffle::hasClauseWithNegatedRelation(), souffle::Adornment::run(), souffle::ResolveAliasesTransformer::transform(), souffle::ReduceExistentialsTransformer::transform(), and souffle::AstTranslator::translateNonRecursiveRelation().
{
         return toPtrVector(clauses);
     }
getLoads()
std::vector<AstLoad*> souffle::AstRelation::getLoads () const inline
Definition at line 331 of file AstRelation.h.
References loads, and souffle::toPtrVector().
Referenced by souffle::AstTranslator::getInputIODirectives().
{
         return toPtrVector(loads);
     }
getName()
const AstRelationIdentifier& souffle::AstRelation::getName () const inline
Return the name of the relation.
Definition at line 83 of file AstRelation.h.
References name.
Referenced by souffle::AstSemanticChecker::checkInlining(), souffle::AstSemanticChecker::checkProgram(), souffle::AstSemanticChecker::checkRelation(), souffle::findInlineCycle(), souffle::AstTranslator::makeIODirective(), souffle::AstNameComparison::operator()(), print(), souffle::SCCGraph::print(), setQualifier(), souffle::transformEqrelRelation(), souffle::AstTranslator::translateNonRecursiveRelation(), souffle::AstTranslator::translateRelation(), souffle::BddBddBTranslator::visitRelation(), and souffle::LogicbloxConverter::visitRelation().
{
         return name;
     }
getQualifier()
int souffle::AstRelation::getQualifier () const inline
Return qualifier associated with this relation.
Definition at line 114 of file AstRelation.h.
References qualifier.
Referenced by souffle::ReduceExistentialsTransformer::transform(), souffle::transformEqrelRelation(), and souffle::updateQualifier().
{
         return qualifier;
     }
getRepresentation()
RelationRepresentation souffle::AstRelation::getRepresentation () const inline
Get representation for this relation.
Definition at line 147 of file AstRelation.h.
References representation.
Referenced by souffle::AstSemanticChecker::checkRelation(), souffle::transformEqrelRelation(), souffle::AstTranslator::translateRelation(), and souffle::updateQualifier().
{
         return representation;
     }
getStores()
std::vector<AstStore*> souffle::AstRelation::getStores () const inline
Definition at line 328 of file AstRelation.h.
References stores, and souffle::toPtrVector().
Referenced by souffle::AstTranslator::getOutputIODirectives().
{
         return toPtrVector(stores);
     }
hasRecordInHead()
bool souffle::AstRelation::hasRecordInHead () const inline
Check whether relation has a record in its head.
Definition at line 171 of file AstRelation.h.
References clauses.
{
         for (auto& cur : clauses) {
             for (auto* arg : cur->getHead()->getArguments()) {
                 if (dynamic_cast<AstRecordInit*>(arg)) {
                     return true;
                 }
             };
         }
         return false;
     }
isInline()
bool souffle::AstRelation::isInline () const inline
Check whether relation is an inlined relation.
Definition at line 166 of file AstRelation.h.
References INLINE_RELATION, and qualifier.
Referenced by souffle::AstSemanticChecker::checkInlining(), souffle::containsInlinedAtom(), souffle::getInlinedLiteral(), and print().
{
         return (qualifier & INLINE_RELATION) != 0;
     }
isOverridable()
bool souffle::AstRelation::isOverridable () const inline
Check whether relation is an overridable relation.
Definition at line 156 of file AstRelation.h.
References OVERRIDABLE_RELATION, and qualifier.
Referenced by print().
{
         return (qualifier & OVERRIDABLE_RELATION) != 0;
     }
isSuppressed()
bool souffle::AstRelation::isSuppressed () const inline
Check whether relation warnings are suppressed.
Definition at line 161 of file AstRelation.h.
References qualifier, and SUPPRESSED_RELATION.
Referenced by souffle::AstSemanticChecker::checkRelation().
{
         return (qualifier & SUPPRESSED_RELATION) != 0;
     }
numberOfHeightParameters()
size_t souffle::AstRelation::numberOfHeightParameters () const inline
Get number of height parameters.
Definition at line 183 of file AstRelation.h.
References clauses, and souffle::Global::config().
Referenced by souffle::getNumberOfHeights(), souffle::AstTranslator::getOutputIODirectives(), and souffle::AstTranslator::translateRelation().
{
         if (Global::config().has("provenance") && Global::config().get("provenance") == "subtreeHeights") {
             size_t maxNrOfPremises = 0;
             for (auto& cur : clauses) {
                 size_t numberOfAtoms = cur->getAtoms().size();
                 if (numberOfAtoms > maxNrOfPremises) maxNrOfPremises = numberOfAtoms;
             }
             return maxNrOfPremises + 1;
         } else {
             return 1;
         }
     }
print()
void souffle::AstRelation::print (std::ostream & os) const inline override virtual
Print string representation of the relation to a given output stream.
Implements souffle::AstNode.
Definition at line 209 of file AstRelation.h.
References attributes, getName(), i, isInline(), isOverridable(), and representation.
{
         os << ".decl " << this->getName() << "(";
         if (!attributes.empty()) {
             os << attributes[0]->getAttributeName() << ":" << attributes[0]->getTypeName();
             for (size_t i = 1; i < attributes.size(); ++i) {
                 os << "," << attributes[i]->getAttributeName() << ":" << attributes[i]->getTypeName();
             }
         }
         os << ") ";
         if (isOverridable()) {
             os << "overridable ";
         }
         if (isInline()) {
             os << "inline ";
         }
         os << representation << " ";
     }
removeClause()
bool souffle::AstRelation::removeClause (const AstClause * clause) inline
Removes the given clause from this relation.
Definition at line 285 of file AstRelation.h.
References clauses.
{
         for (auto it = clauses.begin(); it != clauses.end(); ++it) {
             if (**it == *clause) {
                 clauses.erase(it);
                 return true;
             }
         }
         return false;
     }
setName()
void souffle::AstRelation::setName (const AstRelationIdentifier & n) inline
Set name for this relation.
Definition at line 88 of file AstRelation.h.
References n, and name.
Referenced by souffle::ReduceExistentialsTransformer::transform(), and souffle::MagicSetTransformer::transform().
{
         name = n;
     }
setQualifier()
void souffle::AstRelation::setQualifier (int q) inline
Set qualifier associated with this relation.
Definition at line 119 of file AstRelation.h.
References souffle::BRIE, BRIE_RELATION, souffle::BTREE, BTREE_RELATION, souffle::EQREL, EQREL_RELATION, getName(), souffle::AstNode::getSrcLoc(), INPUT_RELATION, loads, OUTPUT_RELATION, PRINTSIZE_RELATION, q, qualifier, representation, and stores.
Referenced by souffle::transformEqrelRelation(), and souffle::updateQualifier().
{
         qualifier = q;
         if (q & EQREL_RELATION) {
             representation = RelationRepresentation::EQREL;
         } else if (q & BRIE_RELATION) {
             representation = RelationRepresentation::BRIE;
         } else if (q & BTREE_RELATION) {
             representation = RelationRepresentation::BTREE;
         }
         if (q & INPUT_RELATION) {
             loads.emplace_back(new AstLoad());
             loads.back()->setName(getName());
             loads.back()->setSrcLoc(getSrcLoc());
         }
         if (q & OUTPUT_RELATION) {
             stores.emplace_back(new AstStore());
             stores.back()->setName(getName());
             stores.back()->setSrcLoc(getSrcLoc());
         }
         if (q & PRINTSIZE_RELATION) {
             stores.emplace_back(new AstPrintSize());
             stores.back()->setName(getName());
             stores.back()->setSrcLoc(getSrcLoc());
         }
     }
setRepresentation()
void souffle::AstRelation::setRepresentation (RelationRepresentation representation) inline
Definition at line 151 of file AstRelation.h.
References representation.
{
         this->representation = representation;
     }
Friends And Related Function Documentation
operator<< [1/2]
std::ostream& operator<< (std::ostream & os, const AstRelation & rel) friend
Operator overload, calls print if reference is given.
Definition at line 197 of file AstRelation.h.
{
         rel.print(os);
         return os;
     }
operator<< [2/2]
std::ostream& operator<< (std::ostream & os, const AstRelation * rel) friend
Operator overload, prints name if pointer is given.
Definition at line 203 of file AstRelation.h.
{
         os << rel->getName();
         return os;
     }
Field Documentation
attributes
std::vector<std::unique_ptr<AstAttribute> > souffle::AstRelation::attributes protected
Attributes of the relation.
Definition at line 340 of file AstRelation.h.
Referenced by addAttribute(), apply(), clone(), getArity(), getAttribute(), getAttributes(), getChildNodes(), and print().
clauses
std::vector<std::unique_ptr<AstClause> > souffle::AstRelation::clauses protected
Clauses associated with this relation.
Clauses could be either facts or rules.
Definition at line 349 of file AstRelation.h.
Referenced by addClause(), apply(), clauseSize(), clone(), getChildNodes(), getClause(), getClauses(), hasRecordInHead(), numberOfHeightParameters(), and removeClause().
loads
std::vector<std::unique_ptr<AstLoad> > souffle::AstRelation::loads protected
Definition at line 353 of file AstRelation.h.
Referenced by addLoad(), apply(), clone(), getChildNodes(), getLoads(), and setQualifier().
name
AstRelationIdentifier souffle::AstRelation::name protected
Name of relation.
Definition at line 337 of file AstRelation.h.
Referenced by addClause(), clone(), getName(), and setName().
qualifier
int souffle::AstRelation::qualifier = 0 protected
Qualifier of relation (i.e., output or not an output relation)
Definition at line 344 of file AstRelation.h.
Referenced by clone(), getQualifier(), isInline(), isOverridable(), isSuppressed(), and setQualifier().
representation
RelationRepresentation souffle::AstRelation::representation {RelationRepresentation::DEFAULT} protected
Datastructure to use for this relation.
Definition at line 356 of file AstRelation.h.
Referenced by getRepresentation(), print(), setQualifier(), and setRepresentation().
stores
std::vector<std::unique_ptr<AstStore> > souffle::AstRelation::stores protected
IO directives associated with this relation.
Definition at line 352 of file AstRelation.h.
Referenced by addStore(), apply(), clone(), getChildNodes(), getStores(), and setQualifier().
The documentation for this class was generated from the following file:
AstRelation.h