souffle: souffle::AstRecordInit Class Reference
souffle::AstRecordInit Class Reference
An argument that takes a list of values and combines them into a new record.
#include <AstArgument.h>
Public Member Functions
void add (std::unique_ptr< AstArgument > arg)
void apply (const AstNodeMapper &map) override
Mutates this node.
AstRecordInit ()=default
AstRecordInit * clone () const override
Creates a clone of this AST sub-structure.
std::vector< AstArgument * > getArguments () const
std::vector< const AstNode * > getChildNodes () const override
Obtains a list of all embedded child nodes.
void print (std::ostream &os) const override
Output to a given output stream.
~AstRecordInit () override=default
Public Member Functions inherited from souffle::AstArgument
~AstArgument () override=default
Public Member Functions inherited from souffle::AstNode
std::string extloc () const
Return source location of the syntactic element.
SrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (const SrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Implements the node comparison for this node type.
Protected Attributes
std::vector< std::unique_ptr< AstArgument > > args
The list of components to be aggregated into a record.
Detailed Description
An argument that takes a list of values and combines them into a new record.
Definition at line 477 of file AstArgument.h.
Constructor & Destructor Documentation
AstRecordInit()
souffle::AstRecordInit::AstRecordInit () default
~AstRecordInit()
souffle::AstRecordInit::~AstRecordInit () override default
Member Function Documentation
add()
void souffle::AstRecordInit::add (std::unique_ptr< AstArgument > arg) inline
Definition at line 483 of file AstArgument.h.
{
         args.push_back(std::move(arg));
     }
apply()
void souffle::AstRecordInit::apply (const AstNodeMapper & map) inline override virtual
Mutates this node.
Implements souffle::AstNode.
Definition at line 506 of file AstArgument.h.
{
         for (auto& arg : args) {
             arg = map(std::move(arg));
         }
     }
clone()
AstRecordInit* souffle::AstRecordInit::clone () const inline override virtual
Creates a clone of this AST sub-structure.
Implements souffle::AstArgument.
Definition at line 496 of file AstArgument.h.
References souffle::AstNode::getSrcLoc().
{
         auto res = new AstRecordInit();
         for (auto& cur : args) {
             res->args.emplace_back(cur->clone());
         }
         res->setSrcLoc(getSrcLoc());
         return res;
     }
equal()
bool souffle::AstRecordInit::equal (const AstNode & node) const inline override protected virtual
Implements the node comparison for this node type.
Implements souffle::AstNode.
Definition at line 526 of file AstArgument.h.
References souffle::equal_targets().
{
         assert(nullptr != dynamic_cast<const AstRecordInit*>(&node));
         const auto& other = static_cast<const AstRecordInit&>(node);
         return equal_targets(args, other.args);
     }
getArguments()
std::vector<AstArgument*> souffle::AstRecordInit::getArguments () const inline
Definition at line 487 of file AstArgument.h.
References souffle::toPtrVector().
Referenced by souffle::TypeAnalysis::analyseTypes(), souffle::AstSemanticChecker::checkProgram(), souffle::getGroundedTerms(), souffle::RemoveRelationCopiesTransformer::removeRelationCopies(), and souffle::AstTranslator::translateValue().
{
         return toPtrVector(args);
     }
getChildNodes()
std::vector<const AstNode*> souffle::AstRecordInit::getChildNodes () const inline override virtual
Obtains a list of all embedded child nodes.
Reimplemented from souffle::AstArgument.
Definition at line 513 of file AstArgument.h.
References souffle::AstArgument::getChildNodes().
{
         auto res = AstArgument::getChildNodes();
         for (auto& cur : args) {
             res.push_back(cur.get());
         }
         return res;
     }
print()
void souffle::AstRecordInit::print (std::ostream & os) const inline override virtual
Output to a given output stream.
Implements souffle::AstNode.
Definition at line 491 of file AstArgument.h.
References souffle::join().
{
         os << "[" << join(args, ",", print_deref<std::unique_ptr<AstArgument>>()) << "]";
     }
Field Documentation
args
std::vector<std::unique_ptr<AstArgument> > souffle::AstRecordInit::args protected
The list of components to be aggregated into a record.
Definition at line 523 of file AstArgument.h.
The documentation for this class was generated from the following file:
AstArgument.h