souffle: souffle::AstTranslator::ProvenanceClauseTranslator Class Reference
souffle::AstTranslator::ProvenanceClauseTranslator Class Reference
Public Member Functions
ProvenanceClauseTranslator (AstTranslator &translator)
Public Member Functions inherited from souffle::AstTranslator::ClauseTranslator
ClauseTranslator (AstTranslator &translator)
std::unique_ptr< RamStatement > translateClause (const AstClause &clause, const AstClause &originalClause, const int version=0)
generate RAM code for a clause
Protected Member Functions
std::unique_ptr< RamCondition > createCondition (const AstClause &originalClause) override
std::unique_ptr< RamOperation > createOperation (const AstClause &clause) override
Additional Inherited Members
Protected Attributes inherited from souffle::AstTranslator::ClauseTranslator
int level = 0
AstTranslator & translator
ValueIndex valueIndex
Detailed Description
Definition at line 362 of file AstTranslator.h.
Constructor & Destructor Documentation
ProvenanceClauseTranslator()
souffle::AstTranslator::ProvenanceClauseTranslator::ProvenanceClauseTranslator (AstTranslator & translator) inline
Definition at line 368 of file AstTranslator.h.
References souffle::AstTranslator::makeNegationSubproofSubroutine(), souffle::AstTranslator::makeSubproofSubroutine(), souffle::AstTranslator::makeSubproofSubroutineOpt(), souffle::AstTranslator::translateNonRecursiveRelation(), souffle::AstTranslator::translateProgram(), and souffle::AstTranslator::translateRecursiveRelation().
 : ClauseTranslator(translator) {}
Member Function Documentation
createCondition()
std::unique_ptr< RamCondition > souffle::AstTranslator::ProvenanceClauseTranslator::createCondition (const AstClause & originalClause) override protected virtual
Reimplemented from souffle::AstTranslator::ClauseTranslator.
Definition at line 641 of file AstTranslator.cpp.
{
     return nullptr;
 }
createOperation()
std::unique_ptr< RamOperation > souffle::AstTranslator::ProvenanceClauseTranslator::createOperation (const AstClause & clause) override protected virtual
Reimplemented from souffle::AstTranslator::ClauseTranslator.
Definition at line 594 of file AstTranslator.cpp.
References souffle::AstClause::getBodyLiterals(), souffle::getNumberOfHeights(), and i.
{
     std::vector<std::unique_ptr<RamExpression>> values;
     // get all values in the body
     for (AstLiteral* lit : clause.getBodyLiterals()) {
         if (auto atom = dynamic_cast<AstAtom*>(lit)) {
             for (AstArgument* arg : atom->getArguments()) {
                 values.push_back(translator.translateValue(arg, valueIndex));
             }
         } else if (auto neg = dynamic_cast<AstNegation*>(lit)) {
             for (AstArgument* arg : neg->getAtom()->getArguments()) {
                 values.push_back(translator.translateValue(arg, valueIndex));
             }
         } else if (auto con = dynamic_cast<AstBinaryConstraint*>(lit)) {
             values.push_back(translator.translateValue(con->getLHS(), valueIndex));
             values.push_back(translator.translateValue(con->getRHS(), valueIndex));
         } else if (auto neg = dynamic_cast<AstProvenanceNegation*>(lit)) {
             size_t numberOfHeights = getNumberOfHeights(neg->getAtom(), translator.program);
             // non provenance arguments
             for (size_t i = 0; i < neg->getAtom()->getArguments().size() - 1 - numberOfHeights; ++i) {
                 auto arg = neg->getAtom()->getArguments()[i];
                 values.push_back(translator.translateValue(arg, valueIndex));
             }
             // provenance annotation arguments
             for (size_t i = 0; i < numberOfHeights + 1; ++i)
                 values.push_back(std::make_unique<RamNumber>(-1));
         }
     }
     return std::make_unique<RamSubroutineReturnValue>(std::move(values));
 }
The documentation for this class was generated from the following files:
AstTranslator.h
AstTranslator.cpp