souffle: souffle::RamFact Class Reference
souffle::RamFact Class Reference
Insert a fact into a relation.
#include <RamStatement.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
RamFact * clone () const override
Create a clone (i.e.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
std::vector< RamExpression * > getValues () const
Get arguments of fact.
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
RamFact (std::unique_ptr< RamRelationReference > relRef, std::vector< std::unique_ptr< RamExpression >> &&v)
Public Member Functions inherited from souffle::RamRelationStatement
const RamRelation & getRelation () const
Get RAM relation.
RamRelationStatement (std::unique_ptr< RamRelationReference > relRef)
Public Member Functions inherited from souffle::RamStatement
void print (std::ostream &os) const override
Print RAM node.
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, std::unique_ptr< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Attributes
std::vector< std::unique_ptr< RamExpression > > values
Arguments of fact.
Protected Attributes inherited from souffle::RamRelationStatement
std::unique_ptr< RamRelationReference > relationRef
Relation.
Detailed Description
Insert a fact into a relation.
For example, inserting the number 100 into the relation lim:
INSERT (number(100)) INTO lim
Definition at line 403 of file RamStatement.h.
Constructor & Destructor Documentation
RamFact()
souffle::RamFact::RamFact (std::unique_ptr< RamRelationReference > relRef, std::vector< std::unique_ptr< RamExpression >> && v) inline
Definition at line 405 of file RamStatement.h.
             : RamRelationStatement(std::move(relRef)), values(std::move(v)) {}
Member Function Documentation
apply()
void souffle::RamFact::apply (const RamNodeMapper & mapper) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::RamRelationStatement.
Definition at line 436 of file RamStatement.h.
References souffle::RamRelationStatement::apply().
{
         RamRelationStatement::apply(map);
         for (auto& val : values) {
             val = map(std::move(val));
         }
     }
clone()
RamFact* souffle::RamFact::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamStatement.
Definition at line 428 of file RamStatement.h.
References values.
{
         auto* res = new RamFact(std::unique_ptr<RamRelationReference>(relationRef->clone()), {});
         for (auto& cur : values) {
             res->values.emplace_back(cur->clone());
         }
         return res;
     }
equal()
bool souffle::RamFact::equal (const RamNode & other) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamRelationStatement.
Definition at line 447 of file RamStatement.h.
References souffle::RamRelationStatement::equal(), and souffle::equal_targets().
{
         assert(nullptr != dynamic_cast<const RamFact*>(&node));
         const auto& other = static_cast<const RamFact&>(node);
         return RamRelationStatement::equal(other) && equal_targets(values, other.values);
     }
getChildNodes()
std::vector<const RamNode*> souffle::RamFact::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::RamRelationStatement.
Definition at line 420 of file RamStatement.h.
References souffle::RamRelationStatement::getChildNodes().
{
         std::vector<const RamNode*> res = RamRelationStatement::getChildNodes();
         for (const auto& cur : values) {
             res.push_back(cur.get());
         }
         return res;
     }
getValues()
std::vector<RamExpression*> souffle::RamFact::getValues () const inline
Get arguments of fact.
Definition at line 409 of file RamStatement.h.
References souffle::toPtrVector().
Referenced by souffle::Synthesiser::emitCode(), and souffle::NodeGenerator::visitFact().
{
         return toPtrVector(values);
     }
print()
void souffle::RamFact::print (std::ostream & os, int tabpos) const inline override virtual
Pretty print with indentation.
Implements souffle::RamStatement.
Definition at line 413 of file RamStatement.h.
References souffle::join(), and souffle::times().
{
         os << times(" ", tabpos);
         os << "INSERT (" << join(values, ",", print_deref<std::unique_ptr<RamExpression>>()) << ") INTO "
            << getRelation().getName();
         os << std::endl;
     };
Field Documentation
values
std::vector<std::unique_ptr<RamExpression> > souffle::RamFact::values protected
Arguments of fact.
Definition at line 445 of file RamStatement.h.
Referenced by clone().
The documentation for this class was generated from the following file:
RamStatement.h