souffle: souffle::ram::index_utils::DisjointSetIndex< Index > Class Template Reference
souffle::ram::index_utils::DisjointSetIndex< Index > Class Template Reference
A disjoint index is like a direct index storing the indexed elements directly within the maintained index structure.
#include <CompiledIndexUtils.h>
Data Structures
class iterator
Public Types
using operation_hints = typename data_type::operation_hints
Public Member Functions
iterator begin () const
non-const due to binrel find fns
void clear ()
bool contains (const tuple_type &tuple, operation_hints &ctxt) const
Checks whether the data structure contains this tuple tuple The pair to check for.
bool empty () const
iterator end () const
non-const due to binrel find fns
template<typename SubIndex >
range< iterator > equalRange (const tuple_type &tuple, operation_hints &ctxt) const
void extend (const DisjointSetIndex &other)
perform a delta extension, where we union the sets that share elements between this and other.
bool insert (const tuple_type &tuple, operation_hints &ctxt)
Inserts the pair into the equivalence relation.
void insertAll (const DisjointSetIndex &other)
Inserts all pairs from the other disjoint set into this one.
std::vector< range< iterator > > partition (std::size_t np=400) const
Return a list of iterators s.t.
void printHintStatistics (std::ostream &out, const std::string &prefix) const
std::size_t size () const
Static Public Member Functions
static void printDescription (std::ostream &out)
Private Types
using data_type = EquivalenceRelation< tuple_type >
using tuple_type = typename ram::Tuple< RamDomain, 2 >
Static Private Member Functions
static tuple_type orderIn (const tuple_type &tuple)
static tuple_type orderOut (const tuple_type &tuple)
Private Attributes
data_type data
Detailed Description
template<typename Index>
class souffle::ram::index_utils::DisjointSetIndex< Index >
A disjoint index is like a direct index storing the indexed elements directly within the maintained index structure.
However, unlike the B-Tree utilized by a direct index, a disjoint set is utilized, with pairs being implicit.
Template Parameters
Index .. the index to be internally utilized.
Definition at line 1006 of file CompiledIndexUtils.h.
Member Typedef Documentation
data_type
template<typename Index > using souffle::ram::index_utils::DisjointSetIndex< Index >::data_type = EquivalenceRelation<tuple_type> private
Definition at line 1009 of file CompiledIndexUtils.h.
operation_hints
template<typename Index > using souffle::ram::index_utils::DisjointSetIndex< Index >::operation_hints = typename data_type::operation_hints
Definition at line 1014 of file CompiledIndexUtils.h.
tuple_type
template<typename Index > using souffle::ram::index_utils::DisjointSetIndex< Index >::tuple_type = typename ram::Tuple<RamDomain, 2> private
Definition at line 1007 of file CompiledIndexUtils.h.
Member Function Documentation
begin()
template<typename Index > iterator souffle::ram::index_utils::DisjointSetIndex< Index >::begin () const inline
non-const due to binrel find fns
Definition at line 1125 of file CompiledIndexUtils.h.
References souffle::EquivalenceRelation< TupleType >::begin().
{
         return iterator(data.begin());
     }
clear()
template<typename Index > void souffle::ram::index_utils::DisjointSetIndex< Index >::clear () inline
Definition at line 1065 of file CompiledIndexUtils.h.
References souffle::EquivalenceRelation< TupleType >::clear().
                  {
         data.clear();
     }
contains()
template<typename Index > bool souffle::ram::index_utils::DisjointSetIndex< Index >::contains (const tuple_type & tuple, operation_hints & ctxt) const inline
Checks whether the data structure contains this tuple tuple The pair to check for.
Parameters
ctxt context hints to help the query process
Returns
true if the data structure contains this tuple
Definition at line 1032 of file CompiledIndexUtils.h.
References souffle::EquivalenceRelation< TupleType >::contains().
{
         // TODO pnappa: optimisations would include ctxt for .contains()
         // doesn't appear to make much sense for Equivalence, but future optmisations may be made here
         return data.contains(tuple[0], tuple[1]);
     }
empty()
template<typename Index > bool souffle::ram::index_utils::DisjointSetIndex< Index >::empty () const inline
Definition at line 1016 of file CompiledIndexUtils.h.
References souffle::EquivalenceRelation< TupleType >::size().
{
         return data.size() == 0;
     }
end()
template<typename Index > iterator souffle::ram::index_utils::DisjointSetIndex< Index >::end () const inline
non-const due to binrel find fns
Definition at line 1130 of file CompiledIndexUtils.h.
References souffle::EquivalenceRelation< TupleType >::end().
{
         return iterator(data.end());
     }
equalRange()
template<typename Index > template<typename SubIndex > range<iterator> souffle::ram::index_utils::DisjointSetIndex< Index >::equalRange (const tuple_type & tuple, operation_hints & ctxt) const inline
Definition at line 1153 of file CompiledIndexUtils.h.
References souffle::make_range().
{
         static_assert(is_compatible_with<SubIndex, Index>::value, "Invalid sub-index query!");
         auto r = data.template getBoundaries<SubIndex::size>(orderIn(tuple), ctxt);
         return make_range(iterator(r.begin()), iterator(r.end()));
     }
extend()
template<typename Index > void souffle::ram::index_utils::DisjointSetIndex< Index >::extend (const DisjointSetIndex< Index > & other) inline
perform a delta extension, where we union the sets that share elements between this and other.
i.e. if a in this, and a in other, union(set(this->a), set(other->a))
Definition at line 1060 of file CompiledIndexUtils.h.
References souffle::ram::index_utils::DisjointSetIndex< Index >::data, and souffle::EquivalenceRelation< TupleType >::extend().
{
         this->data.extend(other.data);
     }
insert()
template<typename Index > bool souffle::ram::index_utils::DisjointSetIndex< Index >::insert (const tuple_type & tuple, operation_hints & ctxt) inline
Inserts the pair into the equivalence relation.
Parameters
tuple the tuple that contains the value to insert into the data structure
ctxt a context hint which when provided, provides hints to the insertion process with the intention of speeding up insertion
Returns
true if the tuple has not existed in the data structure already
Definition at line 1045 of file CompiledIndexUtils.h.
References souffle::EquivalenceRelation< TupleType >::insert().
{
         return data.insert(tuple[0], tuple[1], ctxt);
     }
insertAll()
template<typename Index > void souffle::ram::index_utils::DisjointSetIndex< Index >::insertAll (const DisjointSetIndex< Index > & other) inline
Inserts all pairs from the other disjoint set into this one.
Parameters
other the supplied disjoint set to copy pairs from
Definition at line 1053 of file CompiledIndexUtils.h.
References souffle::ram::index_utils::DisjointSetIndex< Index >::data, and souffle::EquivalenceRelation< TupleType >::insertAll().
{
         data.insertAll(other.data);
     }
orderIn()
template<typename Index > static tuple_type souffle::ram::index_utils::DisjointSetIndex< Index >::orderIn (const tuple_type & tuple) inline static private
Definition at line 1168 of file CompiledIndexUtils.h.
{
         tuple_type res;
         order<Index>().order_in(res, tuple);
         return res;
     }
orderOut()
template<typename Index > static tuple_type souffle::ram::index_utils::DisjointSetIndex< Index >::orderOut (const tuple_type & tuple) inline static private
Definition at line 1174 of file CompiledIndexUtils.h.
{
         tuple_type res;
         order<Index>().order_out(res, tuple);
         return res;
     }
partition()
template<typename Index > std::vector<range<iterator> > souffle::ram::index_utils::DisjointSetIndex< Index >::partition (std::size_t np = 400) const inline
Return a list of iterators s.t.
we can process in parallel The ordering is not important. The figure 400 is an approximate useful figure, and should be tuned later by another contributor
Parameters
np the number of partitions to attempt to return
Returns
a list of iterators over each partition to return
Definition at line 1141 of file CompiledIndexUtils.h.
References souffle::make_range(), and souffle::EquivalenceRelation< TupleType >::partition().
{
         std::vector<range<iterator>> ret;
         auto val = data.partition(np);
         for (auto& x : val) {
             ret.push_back(make_range(iterator(x.begin()), iterator(x.end())));
         }
         return ret;
     }
printDescription()
template<typename Index > static void souffle::ram::index_utils::DisjointSetIndex< Index >::printDescription (std::ostream & out) inline static
Definition at line 1159 of file CompiledIndexUtils.h.
{
         out << "disjoint-set-index(" << Index() << ")";
     }
printHintStatistics()
template<typename Index > void souffle::ram::index_utils::DisjointSetIndex< Index >::printHintStatistics (std::ostream & out, const std::string & prefix) const inline
Definition at line 1163 of file CompiledIndexUtils.h.
{
         out << prefix << "Disjoint Set Index: no hint statistics supported\n";
     }
size()
template<typename Index > std::size_t souffle::ram::index_utils::DisjointSetIndex< Index >::size () const inline
Definition at line 1022 of file CompiledIndexUtils.h.
References souffle::EquivalenceRelation< TupleType >::size().
{
         return data.size();
     }
Field Documentation
data
template<typename Index > data_type souffle::ram::index_utils::DisjointSetIndex< Index >::data private
Definition at line 1011 of file CompiledIndexUtils.h.
Referenced by souffle::ram::index_utils::DisjointSetIndex< Index >::extend(), and souffle::ram::index_utils::DisjointSetIndex< Index >::insertAll().
The documentation for this class was generated from the following file:
CompiledIndexUtils.h