souffle: souffle::ram::detail::AutoRelation< 0 > Class Template Reference
souffle::ram::detail::AutoRelation< 0 > Class Template Reference
A specialization of a 0-ary relation.
#include <CompiledRelation.h>
Data Structures
class iterator
struct operation_context
Public Types
using tuple_type = typename base::tuple_type
Public Types inherited from souffle::ram::detail::RelationBase< 0, AutoRelation< 0 > >
using tuple_type = Tuple< RamDomain, arity >
Public Member Functions
AutoRelation ()=default
iterator begin () const
bool contains (const tuple_type &=tuple_type(), const operation_context &=operation_context()) const
operation_context createContext ()
bool empty () const
iterator end () const
template<typename Index >
range< iterator > equalRange (const tuple_type &value) const
template<typename Index >
range< iterator > equalRange (const tuple_type &value, operation_context &ctxt) const
template<unsigned... Columns>
range< iterator > equalRange (const tuple_type &value) const
template<unsigned... Columns, typename Context >
range< iterator > equalRange (const tuple_type &value, Context &ctxt) const
bool insert (const RamDomain *ramDomain)
bool insert (const tuple_type &=tuple_type(), const operation_context &=operation_context())
template<typename Setup , typename... Idxs>
void insertAll (const Relation< Setup, 0, Idxs... > &other)
std::vector< range< iterator > > partition () const
std::ostream & printDescription (std::ostream &out=std::cout) const
void printHintStatistics (std::ostream &out, const std::string &prefix="") const
void purge ()
template<typename Index >
range< iterator > scan () const
std::size_t size () const
Public Member Functions inherited from souffle::ram::detail::RelationBase< 0, AutoRelation< 0 > >
bool contains (Args... args) const
bool contains (const tuple_type &tuple) const
std::string getDescription () const
bool insert (Args... args)
bool insert (const RamDomain *ramDomain)
bool insert (const tuple_type &tuple)
void printHintStatistics (std::ostream &out, const std::string &prefix="") const
Private Types
using base = RelationBase< 0, AutoRelation< 0 > >
Private Attributes
bool present = false
Detailed Description
template<>
class souffle::ram::detail::AutoRelation< 0 >
A specialization of a 0-ary relation.
Definition at line 666 of file CompiledRelation.h.
Member Typedef Documentation
base
using souffle::ram::detail::AutoRelation< 0 >::base = RelationBase<0, AutoRelation<0> > private
Definition at line 667 of file CompiledRelation.h.
tuple_type
using souffle::ram::detail::AutoRelation< 0 >::tuple_type = typename base::tuple_type
Definition at line 674 of file CompiledRelation.h.
Constructor & Destructor Documentation
AutoRelation()
souffle::ram::detail::AutoRelation< 0 >::AutoRelation () default
Member Function Documentation
begin()
iterator souffle::ram::detail::AutoRelation< 0 >::begin () const inline
Definition at line 790 of file CompiledRelation.h.
{
         return iterator(present);
     }
contains()
bool souffle::ram::detail::AutoRelation< 0 >::contains (const tuple_type & = tuple_type(), const operation_context & = operation_context()) const inline
Definition at line 743 of file CompiledRelation.h.
{
         return present;
     }
createContext()
operation_context souffle::ram::detail::AutoRelation< 0 >::createContext () inline
Definition at line 731 of file CompiledRelation.h.
{
         return operation_context();
     }
empty()
bool souffle::ram::detail::AutoRelation< 0 >::empty () const inline
Definition at line 735 of file CompiledRelation.h.
{
         return !present;
     }
end()
iterator souffle::ram::detail::AutoRelation< 0 >::end () const inline
Definition at line 794 of file CompiledRelation.h.
{
         return iterator(false);
     }
equalRange() [1/4]
template<typename Index > range<iterator> souffle::ram::detail::AutoRelation< 0 >::equalRange (const tuple_type & value) const inline
Definition at line 769 of file CompiledRelation.h.
References souffle::make_range().
{
         static_assert(std::is_same<Index, index<>>::value, "Requesting uncovered index!");
         return make_range(begin(), end());
     }
equalRange() [2/4]
template<typename Index > range<iterator> souffle::ram::detail::AutoRelation< 0 >::equalRange (const tuple_type & value, operation_context & ctxt) const inline
Definition at line 775 of file CompiledRelation.h.
References souffle::make_range().
{
         static_assert(std::is_same<Index, index<>>::value, "Requesting uncovered index!");
         return make_range(begin(), end());
     }
equalRange() [3/4]
template<unsigned... Columns> range<iterator> souffle::ram::detail::AutoRelation< 0 >::equalRange (const tuple_type & value) const inline
Definition at line 781 of file CompiledRelation.h.
{
         return equalRange<index<Columns...>>(value);
     }
equalRange() [4/4]
template<unsigned... Columns, typename Context > range<iterator> souffle::ram::detail::AutoRelation< 0 >::equalRange (const tuple_type & value, Context & ctxt) const inline
Definition at line 786 of file CompiledRelation.h.
{
         return equalRange<index<Columns...>>(value, ctxt);
     }
insert() [1/2]
bool souffle::ram::detail::AutoRelation< 0 >::insert (const RamDomain * ramDomain) inline
Definition at line 747 of file CompiledRelation.h.
{
         return insert();
     }
insert() [2/2]
bool souffle::ram::detail::AutoRelation< 0 >::insert (const tuple_type & = tuple_type(), const operation_context & = operation_context()) inline
Definition at line 751 of file CompiledRelation.h.
{
         bool res = !present;
         present = true;
         return res;
     }
insertAll()
template<typename Setup , typename... Idxs> void souffle::ram::detail::AutoRelation< 0 >::insertAll (const Relation< Setup, 0, Idxs... > & other) inline
Definition at line 758 of file CompiledRelation.h.
{
         present = present || other.present;
     }
partition()
std::vector<range<iterator> > souffle::ram::detail::AutoRelation< 0 >::partition () const inline
Definition at line 802 of file CompiledRelation.h.
References souffle::make_range(), and souffle::toVector().
{
         return toVector(make_range(begin(), end()));
     }
printDescription()
std::ostream& souffle::ram::detail::AutoRelation< 0 >::printDescription (std::ostream & out = std::cout) const inline
Definition at line 807 of file CompiledRelation.h.
{
         return out << "Nullary Relation";
     }
printHintStatistics()
void souffle::ram::detail::AutoRelation< 0 >::printHintStatistics (std::ostream & out, const std::string & prefix = "") const inline
Definition at line 812 of file CompiledRelation.h.
{
         out << prefix << " -- no hints used in nullary relation --\n";
     }
purge()
void souffle::ram::detail::AutoRelation< 0 >::purge () inline
Definition at line 798 of file CompiledRelation.h.
                  {
         present = false;
     }
scan()
template<typename Index > range<iterator> souffle::ram::detail::AutoRelation< 0 >::scan () const inline
Definition at line 763 of file CompiledRelation.h.
References souffle::make_range().
{
         static_assert(std::is_same<Index, index<>>::value, "Requesting uncovered index!");
         return make_range(begin(), end());
     }
size()
std::size_t souffle::ram::detail::AutoRelation< 0 >::size () const inline
Definition at line 739 of file CompiledRelation.h.
{
         return (present) ? 1 : 0;
     }
Field Documentation
present
bool souffle::ram::detail::AutoRelation< 0 >::present = false private
Definition at line 670 of file CompiledRelation.h.
The documentation for this class was generated from the following file:
CompiledRelation.h