souffle: souffle::AstProgram Class Reference
souffle::AstProgram Class Reference
Intermediate representation of a datalog program that consists of relations, clauses and types.
#include <AstProgram.h>
Public Member Functions
void appendClause (std::unique_ptr< AstClause > clause)
append a new clause to this program – after parsing
void appendRelation (std::unique_ptr< AstRelation > r)
appends a new relation to this program – after parsing
void apply (const AstNodeMapper &map) override
Mutates this node.
AstProgram (const AstProgram &)=delete
Deleted copy constructor since instances can not be copied.
AstProgram (AstProgram &&other) noexcept
A move constructor.
AstProgram * clone () const override
Creates a clone of this AST sub-structure.
std::vector< const AstNode * > getChildNodes () const override
Obtains a list of all embedded child nodes.
std::vector< AstComponentInit * > getComponentInstantiations () const
Obtains a list of all component instantiations.
std::vector< AstComponent * > getComponents () const
Obtains a list of all comprised components.
AstFunctorDeclaration * getFunctorDeclaration (const std::string &name) const
Get functor declaration.
const std::vector< std::unique_ptr< AstLoad > > & getLoads () const
Get all io directives in the program.
std::vector< AstClause * > getOrphanClauses () const
Obtains a list of clauses not associated to any relations.
const std::vector< std::unique_ptr< AstPragma > > & getPragmaDirectives () const
Get all pragma directives in the program.
const std::vector< std::unique_ptr< AstPrintSize > > & getPrintSizes () const
AstRelation * getRelation (const AstRelationIdentifier &name) const
Find and return the relation in the program given its name.
std::vector< AstRelation * > getRelations () const
Get all relations in the program.
const std::vector< std::unique_ptr< AstStore > > & getStores () const
const AstType * getType (const AstTypeIdentifier &name) const
Obtains the type with the given name.
std::vector< const AstType * > getTypes () const
Gets a list of all types in this program.
void print (std::ostream &os) const override
Output the program to a given output stream.
size_t relationSize () const
Return the number of relations in the program.
void removeClause (const AstClause *clause)
Removes a clause from this program.
void removeRelation (const AstRelationIdentifier &name)
Remove a relation from the program.
~AstProgram () override=default
A programs destructor.
Public Member Functions inherited from souffle::AstNode
std::string extloc () const
Return source location of the syntactic element.
SrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (const SrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Implements the node comparison for this node type.
Private Member Functions
void addClause (std::unique_ptr< AstClause > clause)
Add a clause to the program.
void addComponent (std::unique_ptr< AstComponent > c)
Adds the given component to this program.
void addFunctorDeclaration (std::unique_ptr< souffle::AstFunctorDeclaration > f)
Add a functor to the program.
void addInstantiation (std::unique_ptr< AstComponentInit > i)
Adds a component instantiation.
void addLoad (std::unique_ptr< AstLoad > directive)
Add an IO directive to the program.
void addPragma (std::unique_ptr< AstPragma > r)
Add a pragma to the program.
void addPrintSize (std::unique_ptr< AstPrintSize > directive)
void addRelation (std::unique_ptr< AstRelation > r)
Add the given relation to the program.
void addStore (std::unique_ptr< AstStore > directive)
void addType (std::unique_ptr< AstType > type)
Add the given type to the program.
AstProgram ()=default
a private constructor to restrict creation
void finishParsing ()
Private Attributes
std::vector< std::unique_ptr< AstClause > > clauses
The list of clauses provided by the user.
std::vector< std::unique_ptr< AstComponent > > components
Program components.
std::map< std::string, std::unique_ptr< AstFunctorDeclaration > > functors
External Functors.
std::vector< std::unique_ptr< AstComponentInit > > instantiations
Component instantiations.
std::vector< std::unique_ptr< AstLoad > > loads
The list of IO directives provided by the user.
std::vector< std::unique_ptr< AstPragma > > pragmaDirectives
Pragmas.
std::vector< std::unique_ptr< AstPrintSize > > printSizes
std::map< AstRelationIdentifier, std::unique_ptr< AstRelation > > relations
Program relations.
std::vector< std::unique_ptr< AstStore > > stores
std::map< AstTypeIdentifier, std::unique_ptr< AstType > > types
Program types.
Friends
class ComponentInstantiationTransformer
class ParserDriver
class ProvenanceTransformer
Detailed Description
Intermediate representation of a datalog program that consists of relations, clauses and types.
Definition at line 50 of file AstProgram.h.
Constructor & Destructor Documentation
AstProgram() [1/3]
souffle::AstProgram::AstProgram (const AstProgram &) delete
Deleted copy constructor since instances can not be copied.
AstProgram() [2/3]
souffle::AstProgram::AstProgram (AstProgram && other) noexcept
A move constructor.
Definition at line 34 of file AstProgram.cpp.
References loads, relations, stores, and types.
{
     types.swap(other.types);
     relations.swap(other.relations);
     clauses.swap(other.clauses);
     loads.swap(other.loads);
     stores.swap(other.stores);
     components.swap(other.components);
     instantiations.swap(other.instantiations);
 }
~AstProgram()
souffle::AstProgram::~AstProgram () override default
A programs destructor.
AstProgram() [3/3]
souffle::AstProgram::AstProgram () private default
a private constructor to restrict creation
Referenced by clone().
Member Function Documentation
addClause()
void souffle::AstProgram::addClause (std::unique_ptr< AstClause > clause) private
Add a clause to the program.
Definition at line 124 of file AstProgram.cpp.
References clauses.
{
     assert(clause && "NULL clause");
     clauses.push_back(std::move(clause));
 }
addComponent()
void souffle::AstProgram::addComponent (std::unique_ptr< AstComponent > c) inline private
Adds the given component to this program.
Definition at line 294 of file AstProgram.h.
{
         components.push_back(std::move(c));
     }
addFunctorDeclaration()
void souffle::AstProgram::addFunctorDeclaration (std::unique_ptr< souffle::AstFunctorDeclaration > f) private
Add a functor to the program.
Definition at line 81 of file AstProgram.cpp.
References functors.
{
     const auto& name = f->getName();
     assert(functors.find(name) == functors.end() && "Redefinition of relation!");
     functors[name] = std::move(f);
 }
addInstantiation()
void souffle::AstProgram::addInstantiation (std::unique_ptr< AstComponentInit > i) inline private
Adds a component instantiation.
Definition at line 299 of file AstProgram.h.
References finishParsing().
{
         instantiations.push_back(std::move(i));
     }
addLoad()
void souffle::AstProgram::addLoad (std::unique_ptr< AstLoad > directive) private
Add an IO directive to the program.
Definition at line 129 of file AstProgram.cpp.
References loads.
{
     assert(directive && "NULL IO directive");
     loads.push_back(std::move(directive));
 }
addPragma()
void souffle::AstProgram::addPragma (std::unique_ptr< AstPragma > r) private
Add a pragma to the program.
Definition at line 140 of file AstProgram.cpp.
References pragmaDirectives.
{
     assert(pragma && "NULL IO directive");
     pragmaDirectives.push_back(std::move(pragma));
 }
addPrintSize()
void souffle::AstProgram::addPrintSize (std::unique_ptr< AstPrintSize > directive) private
addRelation()
void souffle::AstProgram::addRelation (std::unique_ptr< AstRelation > r) private
Add the given relation to the program.
Asserts if a relation with the same name has already been added.
Definition at line 65 of file AstProgram.cpp.
References relations.
{
     const auto& name = r->getName();
     assert(relations.find(name) == relations.end() && "Redefinition of relation!");
     relations[name] = std::move(r);
 }
addStore()
void souffle::AstProgram::addStore (std::unique_ptr< AstStore > directive) private
Definition at line 134 of file AstProgram.cpp.
References stores.
{
     assert(directive && "NULL IO directive");
     stores.push_back(std::move(directive));
 }
addType()
void souffle::AstProgram::addType (std::unique_ptr< AstType > type) private
Add the given type to the program.
Asserts if a type with the same name has already been added.
Definition at line 45 of file AstProgram.cpp.
References types.
{
     auto& cur = types[type->getName()];
     assert(!cur && "Redefinition of type!");
     cur = std::move(type);
 }
appendClause()
void souffle::AstProgram::appendClause (std::unique_ptr< AstClause > clause)
append a new clause to this program – after parsing
Definition at line 93 of file AstProgram.cpp.
References relations.
Referenced by relationSize(), souffle::RemoveEmptyRelationsTransformer::removeEmptyRelationUses(), souffle::separateDBs(), souffle::ResolveAliasesTransformer::transform(), souffle::InlineRelationsTransformer::transform(), souffle::PartitionBodyLiteralsTransformer::transform(), and souffle::MagicSetTransformer::transform().
{
     // get relation
     std::unique_ptr<AstRelation>& r = relations[clause->getHead()->getName()];
     assert(r && "Trying to append to unknown relation!");
     // delegate call
     r->addClause(std::move(clause));
 }
appendRelation()
void souffle::AstProgram::appendRelation (std::unique_ptr< AstRelation > r)
appends a new relation to this program – after parsing
Definition at line 71 of file AstProgram.cpp.
References relations.
Referenced by souffle::MaterializeAggregationQueriesTransformer::materializeAggregationQueries(), relationSize(), souffle::separateDBs(), souffle::PartitionBodyLiteralsTransformer::transform(), souffle::ReduceExistentialsTransformer::transform(), and souffle::MagicSetTransformer::transform().
{
     // get relation
     std::unique_ptr<AstRelation>& rel = relations[r->getName()];
     assert(!rel && "Adding pre-existing relation!");
     // add relation
     rel = std::move(r);
 }
apply()
void souffle::AstProgram::apply (const AstNodeMapper & map) override virtual
Mutates this node.
Implements souffle::AstNode.
Definition at line 292 of file AstProgram.cpp.
References components, instantiations, loads, pragmaDirectives, relations, stores, and types.
Referenced by getComponentInstantiations(), souffle::nameInlinedUnderscores(), souffle::RemoveBooleanConstraintsTransformer::transform(), souffle::ReduceExistentialsTransformer::transform(), souffle::RemoveRedundantSumsTransformer::transform(), and souffle::RemoveTypecastsTransformer::transform().
{
     for (auto& cur : types) {
         cur.second = map(std::move(cur.second));
     }
     for (auto& cur : relations) {
         cur.second = map(std::move(cur.second));
     }
     for (auto& cur : components) {
         cur = map(std::move(cur));
     }
     for (auto& cur : instantiations) {
         cur = map(std::move(cur));
     }
     for (auto& cur : pragmaDirectives) {
         cur = map(std::move(cur));
     }
     for (auto& cur : loads) {
         cur = map(std::move(cur));
     }
     for (auto& cur : stores) {
         cur = map(std::move(cur));
     }
 }
clone()
AstProgram * souffle::AstProgram::clone () const override virtual
Creates a clone of this AST sub-structure.
Implements souffle::AstNode.
Definition at line 241 of file AstProgram.cpp.
References AstProgram(), clauses, components, functors, instantiations, loads, pragmaDirectives, printSizes, relations, stores, and types.
Referenced by getComponentInstantiations().
{
     auto res = new AstProgram();
     // move types
     for (const auto& cur : types) {
         res->types.insert(std::make_pair(cur.first, std::unique_ptr<AstType>(cur.second->clone())));
     }
     for (const auto& cur : relations) {
         res->relations.insert(std::make_pair(cur.first, std::unique_ptr<AstRelation>(cur.second->clone())));
     }
     for (const auto& cur : functors) {
         res->functors.insert(
                 std::make_pair(cur.first, std::unique_ptr<AstFunctorDeclaration>(cur.second->clone())));
     }
     for (const auto& cur : clauses) {
         res->clauses.emplace_back(cur->clone());
     }
     for (const auto& cur : loads) {
         res->loads.emplace_back(cur->clone());
     }
     for (const auto& cur : printSizes) {
         res->printSizes.emplace_back(cur->clone());
     }
     for (const auto& cur : stores) {
         res->stores.emplace_back(cur->clone());
     }
     for (const auto& cur : components) {
         res->components.emplace_back(cur->clone());
     }
     for (const auto& cur : instantiations) {
         res->instantiations.emplace_back(cur->clone());
     }
     for (const auto& cur : pragmaDirectives) {
         res->pragmaDirectives.emplace_back(cur->clone());
     }
     ErrorReport errors;
     res->finishParsing();
     // done
     return res;
 }
equal()
bool souffle::AstProgram::equal (const AstNode & node) const inline override protected virtual
Implements the node comparison for this node type.
Implements souffle::AstNode.
Definition at line 173 of file AstProgram.h.
References clauses, components, souffle::equal_targets(), instantiations, loads, printSizes, relations, stores, and types.
{
         assert(nullptr != dynamic_cast<const AstProgram*>(&node));
         const auto& other = static_cast<const AstProgram&>(node);
         // check list sizes
         if (types.size() != other.types.size()) {
             return false;
         }
         if (relations.size() != other.relations.size()) {
             return false;
         }
         // check types
         for (const auto& cur : types) {
             auto pos = other.types.find(cur.first);
             if (pos == other.types.end()) {
                 return false;
             }
             if (*cur.second != *pos->second) {
                 return false;
             }
         }
         // check relations
         for (const auto& cur : relations) {
             auto pos = other.relations.find(cur.first);
             if (pos == other.relations.end()) {
                 return false;
             }
             if (*cur.second != *pos->second) {
                 return false;
             }
         }
         // check components
         if (!equal_targets(components, other.components)) {
             return false;
         }
         if (!equal_targets(instantiations, other.instantiations)) {
             return false;
         }
         if (!equal_targets(clauses, other.clauses)) {
             return false;
         }
         if (!equal_targets(loads, other.loads)) {
             return false;
         }
         if (!equal_targets(printSizes, other.printSizes)) {
             return false;
         }
         if (!equal_targets(stores, other.stores)) {
             return false;
         }
         // no different found => programs are equal
         return true;
     }
finishParsing()
void souffle::AstProgram::finishParsing () private
Definition at line 316 of file AstProgram.cpp.
References clauses, loads, relations, and stores.
Referenced by addInstantiation().
{
     // unbound clauses with no relation defined
     std::vector<std::unique_ptr<AstClause>> unbound;
     // add clauses
     for (auto& cur : clauses) {
         auto pos = relations.find(cur->getHead()->getName());
         if (pos != relations.end()) {
             pos->second->addClause(std::move(cur));
         } else {
             unbound.push_back(std::move(cur));
         }
     }
     // remember the remaining orphan clauses
     clauses.clear();
     clauses.swap(unbound);
     // unbound directives with no relation defined
     std::vector<std::unique_ptr<AstLoad>> unboundLoads;
     std::vector<std::unique_ptr<AstStore>> unboundStores;
     // add IO directives
     for (auto& cur : loads) {
         auto pos = relations.find(cur->getName());
         if (pos != relations.end()) {
             pos->second->addLoad(std::move(cur));
         } else {
             unboundLoads.push_back(std::move(cur));
         }
     }
     // remember the remaining orphan directives
     loads.clear();
     loads.swap(unboundLoads);
     for (auto& cur : stores) {
         auto pos = relations.find(cur->getName());
         if (pos != relations.end()) {
             pos->second->addStore(std::move(cur));
         } else {
             unboundStores.push_back(std::move(cur));
         }
     }
     // remember the remaining orphan directives
     stores.clear();
     stores.swap(unboundStores);
 }
getChildNodes()
std::vector<const AstNode*> souffle::AstProgram::getChildNodes () const inline override virtual
Obtains a list of all embedded child nodes.
Implements souffle::AstNode.
Definition at line 139 of file AstProgram.h.
References clauses, components, instantiations, loads, pragmaDirectives, printSizes, relations, stores, and types.
{
         std::vector<const AstNode*> res;
         for (const auto& cur : types) {
             res.push_back(cur.second.get());
         }
         for (const auto& cur : relations) {
             res.push_back(cur.second.get());
         }
         for (const auto& cur : components) {
             res.push_back(cur.get());
         }
         for (const auto& cur : instantiations) {
             res.push_back(cur.get());
         }
         for (const auto& cur : clauses) {
             res.push_back(cur.get());
         }
         for (const auto& cur : pragmaDirectives) {
             res.push_back(cur.get());
         }
         for (const auto& cur : loads) {
             res.push_back(cur.get());
         }
         for (const auto& cur : printSizes) {
             res.push_back(cur.get());
         }
         for (const auto& cur : stores) {
             res.push_back(cur.get());
         }
         return res;
     }
getComponentInstantiations()
std::vector<AstComponentInit*> souffle::AstProgram::getComponentInstantiations () const inline
Obtains a list of all component instantiations.
Definition at line 121 of file AstProgram.h.
References apply(), clone(), instantiations, print(), and souffle::toPtrVector().
Referenced by souffle::AstComponentChecker::checkComponentNamespaces(), and souffle::AstComponentChecker::checkComponents().
{
         return toPtrVector(instantiations);
     }
getComponents()
std::vector<AstComponent*> souffle::AstProgram::getComponents () const inline
Obtains a list of all comprised components.
Definition at line 116 of file AstProgram.h.
References components, and souffle::toPtrVector().
Referenced by souffle::AstComponentChecker::checkComponentNamespaces(), souffle::AstComponentChecker::checkComponents(), and souffle::ComponentLookup::run().
{
         return toPtrVector(components);
     }
getFunctorDeclaration()
AstFunctorDeclaration * souffle::AstProgram::getFunctorDeclaration (const std::string & name) const
Get functor declaration.
Definition at line 118 of file AstProgram.cpp.
References functors.
Referenced by souffle::TypeAnalysis::analyseTypes(), and souffle::AstTranslator::translateValue().
{
     auto pos = functors.find(name);
     return (pos == functors.end()) ? nullptr : pos->second.get();
 }
getLoads()
const std::vector< std::unique_ptr< AstLoad > > & souffle::AstProgram::getLoads () const
Get all io directives in the program.
Definition at line 160 of file AstProgram.cpp.
References loads.
Referenced by souffle::AstSemanticChecker::checkIODirectives().
{
     return loads;
 }
getOrphanClauses()
std::vector<AstClause*> souffle::AstProgram::getOrphanClauses () const inline
Obtains a list of clauses not associated to any relations.
In a valid program this list is always empty
Definition at line 109 of file AstProgram.h.
References clauses, and souffle::toPtrVector().
Referenced by souffle::AstSemanticChecker::checkRules().
{
         return toPtrVector(clauses);
     }
getPragmaDirectives()
const std::vector< std::unique_ptr< AstPragma > > & souffle::AstProgram::getPragmaDirectives () const
Get all pragma directives in the program.
Definition at line 146 of file AstProgram.cpp.
References pragmaDirectives.
{
     return pragmaDirectives;
 }
getPrintSizes()
const std::vector<std::unique_ptr<AstPrintSize> >& souffle::AstProgram::getPrintSizes () const
getRelation()
AstRelation * souffle::AstProgram::getRelation (const AstRelationIdentifier & name) const
Find and return the relation in the program given its name.
Definition at line 113 of file AstProgram.cpp.
References relations.
Referenced by souffle::addForwardDependencies(), souffle::AstSemanticChecker::checkAtom(), souffle::AstSemanticChecker::checkFact(), souffle::AstSemanticChecker::checkInlining(), souffle::AstSemanticChecker::checkIODirectives(), souffle::RecursiveClauses::computeIsRecursive(), souffle::containsInlinedAtom(), souffle::formNegatedLiterals(), souffle::getAtomRelation(), souffle::getInlinedLiteral(), souffle::getNextEdbName(), souffle::getNumberOfHeights(), souffle::AstTranslator::makeNegationSubproofSubroutine(), souffle::AstTranslator::makeSubproofSubroutine(), souffle::MaterializeAggregationQueriesTransformer::materializeAggregationQueries(), souffle::IOType::run(), souffle::Adornment::run(), souffle::ReduceExistentialsTransformer::transform(), and souffle::MagicSetTransformer::transform().
{
     auto pos = relations.find(name);
     return (pos == relations.end()) ? nullptr : pos->second.get();
 }
getRelations()
std::vector< AstRelation * > souffle::AstProgram::getRelations () const
Get all relations in the program.
Definition at line 151 of file AstProgram.cpp.
References relations.
Referenced by souffle::addBackwardDependencies(), souffle::addIgnoredRelations(), souffle::bindComposites(), souffle::AstComponentChecker::checkComponentNamespaces(), souffle::AstSemanticChecker::checkInlining(), souffle::AstSemanticChecker::checkNamespaces(), souffle::AstSemanticChecker::checkRules(), souffle::nameInlinedUnderscores(), souffle::normaliseInlinedHeads(), souffle::RemoveEmptyRelationsTransformer::removeEmptyRelations(), souffle::replaceUnderscores(), souffle::TypeAnalysis::run(), souffle::PrecedenceGraph::run(), souffle::RedundantRelations::run(), souffle::SCCGraph::run(), souffle::Adornment::run(), souffle::separateDBs(), souffle::MinimiseProgramTransformer::transform(), souffle::RemoveBooleanConstraintsTransformer::transform(), souffle::InlineRelationsTransformer::transform(), souffle::ReduceExistentialsTransformer::transform(), souffle::ReplaceSingletonVariablesTransformer::transform(), souffle::ReorderLiteralsTransformer::transform(), souffle::NormaliseConstraintsTransformer::transform(), souffle::AstTranslator::translateProgram(), souffle::BddBddBTranslator::visitProgram(), and souffle::LogicbloxConverter::visitProgram().
{
     std::vector<AstRelation*> res;
     for (const auto& rel : relations) {
         res.push_back(rel.second.get());
     }
     return res;
 }
getStores()
const std::vector< std::unique_ptr< AstStore > > & souffle::AstProgram::getStores () const
Definition at line 165 of file AstProgram.cpp.
References stores.
Referenced by souffle::AstSemanticChecker::checkIODirectives().
{
     return stores;
 }
getType()
const AstType * souffle::AstProgram::getType (const AstTypeIdentifier & name) const
Obtains the type with the given name.
Definition at line 51 of file AstProgram.cpp.
References types.
Referenced by souffle::AstSemanticChecker::checkRecordType(), souffle::AstSemanticChecker::checkRelationDeclaration(), souffle::AstSemanticChecker::checkUnionType(), souffle::unionContainsNumber(), and souffle::unionContainsSymbol().
{
     auto pos = types.find(name);
     return (pos == types.end()) ? nullptr : pos->second.get();
 }
getTypes()
std::vector< const AstType * > souffle::AstProgram::getTypes () const
Gets a list of all types in this program.
Definition at line 56 of file AstProgram.cpp.
References types.
Referenced by souffle::AstComponentChecker::checkComponentNamespaces(), souffle::AstSemanticChecker::checkNamespaces(), souffle::AstSemanticChecker::checkRecursiveUnionTypes(), souffle::AstSemanticChecker::checkTypes(), and souffle::TypeEnvironmentAnalysis::updateTypeEnvironment().
{
     std::vector<const AstType*> res;
     for (const auto& cur : types) {
         res.push_back(cur.second.get());
     }
     return res;
 }
print()
void souffle::AstProgram::print (std::ostream & os) const override virtual
Output the program to a given output stream.
Implements souffle::AstNode.
Definition at line 170 of file AstProgram.cpp.
References clauses, components, functors, instantiations, souffle::join(), loads, pragmaDirectives, relations, stores, and types.
Referenced by souffle::DebugReporter::generateDebugReport(), and getComponentInstantiations().
{
     /* Print types */
     os << "// ----- Types -----\n";
     for (const auto& cur : types) {
         os << *cur.second << "\n";
     }
     /* Print components */
     if (!components.empty()) {
         os << "\n// ----- Components -----\n";
         for (const auto& cur : components) {
             os << *cur << "\n";
         }
     }
     /* Print instantiations */
     if (!instantiations.empty()) {
         os << "\n";
         for (const auto& cur : instantiations) {
             os << *cur << "\n";
         }
     }
     /* Print functors */
     os << "\n// ----- Functors -----\n";
     for (const auto& cur : functors) {
         const std::unique_ptr<AstFunctorDeclaration>& f = cur.second;
         os << "\n\n// -- " << f->getName() << " --\n";
         f->print(os);
         os << "\n";
     }
     /* Print relations */
     os << "\n// ----- Relations -----\n";
     for (const auto& cur : relations) {
         const std::unique_ptr<AstRelation>& rel = cur.second;
         os << "\n\n// -- " << rel->getName() << " --\n";
         os << *rel << "\n\n";
         for (const auto clause : rel->getClauses()) {
             os << *clause << "\n\n";
         }
         for (const auto ioDirective : rel->getLoads()) {
             os << *ioDirective << "\n\n";
         }
         for (const auto ioDirective : rel->getStores()) {
             os << *ioDirective << "\n\n";
         }
     }
     if (!clauses.empty()) {
         os << "\n// ----- Orphan Clauses -----\n";
         os << join(clauses, "\n\n", print_deref<std::unique_ptr<AstClause>>()) << "\n";
     }
     if (!loads.empty()) {
         os << "\n// ----- Orphan Load directives -----\n";
         os << join(loads, "\n\n", print_deref<std::unique_ptr<AstLoad>>()) << "\n";
     }
     if (!stores.empty()) {
         os << "\n// ----- Orphan Store directives -----\n";
         os << join(stores, "\n\n", print_deref<std::unique_ptr<AstStore>>()) << "\n";
     }
     if (!pragmaDirectives.empty()) {
         os << "\n// ----- Pragma -----\n";
         for (const auto& cur : pragmaDirectives) {
             os << *cur << "\n";
         }
     }
 }
relationSize()
size_t souffle::AstProgram::relationSize () const inline
Return the number of relations in the program.
Definition at line 89 of file AstProgram.h.
References appendClause(), appendRelation(), relations, removeClause(), and removeRelation().
{
         return relations.size();
     }
removeClause()
void souffle::AstProgram::removeClause (const AstClause * clause)
Removes a clause from this program.
Definition at line 102 of file AstProgram.cpp.
References souffle::AstClause::getHead(), souffle::AstAtom::getName(), and relations.
Referenced by souffle::normaliseInlinedHeads(), relationSize(), souffle::RemoveEmptyRelationsTransformer::removeEmptyRelationUses(), souffle::ResolveAliasesTransformer::transform(), souffle::MinimiseProgramTransformer::transform(), souffle::InlineRelationsTransformer::transform(), and souffle::PartitionBodyLiteralsTransformer::transform().
{
     // get relation
     auto pos = relations.find(clause->getHead()->getName());
     if (pos == relations.end()) {
         return;
     }
     // delegate call
     pos->second->removeClause(clause);
 }
removeRelation()
void souffle::AstProgram::removeRelation (const AstRelationIdentifier & name)
Remove a relation from the program.
Definition at line 88 of file AstProgram.cpp.
References relations.
Referenced by relationSize(), souffle::RemoveEmptyRelationsTransformer::removeEmptyRelations(), souffle::RemoveRedundantRelationsTransformer::transform(), and souffle::MagicSetTransformer::transform().
{
     /* Remove relation from map */
     relations.erase(relations.find(name));
 }
Friends And Related Function Documentation
ComponentInstantiationTransformer
friend class ComponentInstantiationTransformer friend
Definition at line 232 of file AstProgram.h.
ParserDriver
friend class ParserDriver friend
Definition at line 233 of file AstProgram.h.
ProvenanceTransformer
friend class ProvenanceTransformer friend
Definition at line 234 of file AstProgram.h.
Field Documentation
clauses
std::vector<std::unique_ptr<AstClause> > souffle::AstProgram::clauses private
The list of clauses provided by the user.
Definition at line 246 of file AstProgram.h.
Referenced by addClause(), clone(), equal(), finishParsing(), getChildNodes(), getOrphanClauses(), print(), and souffle::ComponentInstantiationTransformer::transform().
components
std::vector<std::unique_ptr<AstComponent> > souffle::AstProgram::components private
Program components.
Definition at line 254 of file AstProgram.h.
Referenced by apply(), clone(), equal(), getChildNodes(), getComponents(), print(), and souffle::ComponentInstantiationTransformer::transform().
functors
std::map<std::string, std::unique_ptr<AstFunctorDeclaration> > souffle::AstProgram::functors private
External Functors.
Definition at line 243 of file AstProgram.h.
Referenced by addFunctorDeclaration(), clone(), getFunctorDeclaration(), and print().
instantiations
std::vector<std::unique_ptr<AstComponentInit> > souffle::AstProgram::instantiations private
Component instantiations.
Definition at line 257 of file AstProgram.h.
Referenced by apply(), clone(), equal(), getChildNodes(), getComponentInstantiations(), print(), and souffle::ComponentInstantiationTransformer::transform().
loads
std::vector<std::unique_ptr<AstLoad> > souffle::AstProgram::loads private
The list of IO directives provided by the user.
Definition at line 249 of file AstProgram.h.
Referenced by addLoad(), apply(), clone(), equal(), finishParsing(), getChildNodes(), getLoads(), print(), and souffle::ComponentInstantiationTransformer::transform().
pragmaDirectives
std::vector<std::unique_ptr<AstPragma> > souffle::AstProgram::pragmaDirectives private
Pragmas.
Definition at line 260 of file AstProgram.h.
Referenced by addPragma(), apply(), clone(), getChildNodes(), getPragmaDirectives(), and print().
printSizes
std::vector<std::unique_ptr<AstPrintSize> > souffle::AstProgram::printSizes private
Definition at line 250 of file AstProgram.h.
Referenced by clone(), equal(), getChildNodes(), and souffle::ComponentInstantiationTransformer::transform().
relations
std::map<AstRelationIdentifier, std::unique_ptr<AstRelation> > souffle::AstProgram::relations private
Program relations.
Definition at line 240 of file AstProgram.h.
Referenced by addRelation(), appendClause(), appendRelation(), apply(), clone(), equal(), finishParsing(), getChildNodes(), getRelation(), getRelations(), print(), relationSize(), removeClause(), removeRelation(), and souffle::ComponentInstantiationTransformer::transform().
stores
std::vector<std::unique_ptr<AstStore> > souffle::AstProgram::stores private
Definition at line 251 of file AstProgram.h.
Referenced by addStore(), apply(), clone(), equal(), finishParsing(), getChildNodes(), getStores(), print(), and souffle::ComponentInstantiationTransformer::transform().
types
std::map<AstTypeIdentifier, std::unique_ptr<AstType> > souffle::AstProgram::types private
Program types.
Definition at line 237 of file AstProgram.h.
Referenced by addType(), apply(), clone(), equal(), getChildNodes(), getType(), getTypes(), print(), and souffle::ComponentInstantiationTransformer::transform().
The documentation for this class was generated from the following files:
AstProgram.h
AstProgram.cpp