souffle: souffle::WriteStreamCSV Class Reference
souffle::WriteStreamCSV Class Reference
#include <WriteStreamCSV.h>
Protected Member Functions
virtual std::string getDelimiter (const IODirectives &ioDirectives) const
Detailed Description
Definition at line 33 of file WriteStreamCSV.h.
Member Function Documentation
getDelimiter()
virtual std::string souffle::WriteStreamCSV::getDelimiter (const IODirectives & ioDirectives) const inline protected virtual
Definition at line 35 of file WriteStreamCSV.h.
References souffle::IODirectives::get(), and souffle::IODirectives::has().
Referenced by souffle::WriteFileCSV::writeNextTuple().
{
         if (ioDirectives.has("delimiter")) {
             return ioDirectives.get("delimiter");
         }
         return "\t";
     }
The documentation for this class was generated from the following file:
WriteStreamCSV.h