souffle: souffle::ExpandFilterTransformer Class Reference
souffle::ExpandFilterTransformer Class Reference
Transforms RamConjunctions into consecutive filter operations.
#include <RamTransforms.h>
Public Member Functions
bool expandFilters (RamProgram &program)
Expand filter operations.
std::string getName () const override
get name of the transformer
Public Member Functions inherited from souffle::RamTransformer
bool apply (RamTranslationUnit &translationUnit)
apply the transformer to a translation unit translationUnit that will be transformed.
virtual ~RamTransformer ()=default
Protected Member Functions
bool transform (RamTranslationUnit &translationUnit) override
transform the translation unit / used by apply translationUnit that will be transformed.
Detailed Description
Transforms RamConjunctions into consecutive filter operations.
For example ..
QUERY
 ...
  IF C1 /\ C2 then
   ...
will be rewritten to
QUERY
 ...
  IF C1
   IF C2
    ...
Definition at line 54 of file RamTransforms.h.
Member Function Documentation
expandFilters()
bool souffle::ExpandFilterTransformer::expandFilters (RamProgram & program)
Expand filter operations.
Parameters
program Program that is transformed
Returns
Flag showing whether the program has been changed by the transformation
Definition at line 33 of file RamTransforms.cpp.
References souffle::RamTransformer::apply(), souffle::makeLambdaRamMapper(), souffle::toConjunctionList(), and souffle::visitDepthFirst().
Referenced by getName(), and transform().
{
     // flag to determine whether the RAM program has changed
     bool changed = false;
     visitDepthFirst(program, [&](const RamQuery& query) {
         std::function<std::unique_ptr<RamNode>(std::unique_ptr<RamNode>)> filterRewriter =
                 [&](std::unique_ptr<RamNode> node) -> std::unique_ptr<RamNode> {
             if (const RamFilter* filter = dynamic_cast<RamFilter*>(node.get())) {
                 const RamCondition* condition = &filter->getCondition();
                 std::vector<std::unique_ptr<RamCondition>> conditionList = toConjunctionList(condition);
                 if (conditionList.size() > 1) {
                     changed = true;
                     std::vector<std::unique_ptr<RamFilter>> filters;
                     for (auto iter = conditionList.begin(); iter != conditionList.end(); ++iter) {
                         auto& cond = *iter;
                         auto tempCond = cond->clone();
                         if (filters.empty()) {
                             filters.emplace_back(std::make_unique<RamFilter>(
                                     std::unique_ptr<RamCondition>(std::move(tempCond)),
                                     std::unique_ptr<RamOperation>(filter->getOperation().clone())));
                         } else {
                             filters.emplace_back(std::make_unique<RamFilter>(
                                     std::unique_ptr<RamCondition>(std::move(tempCond)),
                                     std::move(filters.back())));
                         }
                     }
                     node = std::move(filters.back());
                 }
             }
             node->apply(makeLambdaRamMapper(filterRewriter));
             return node;
         };
         const_cast<RamQuery*>(&query)->apply(makeLambdaRamMapper(filterRewriter));
     });
     return changed;
 }
getName()
std::string souffle::ExpandFilterTransformer::getName () const inline override virtual
get name of the transformer
Implements souffle::RamTransformer.
Definition at line 56 of file RamTransforms.h.
References expandFilters().
{
         return "ExpandFilterTransformer";
     }
transform()
bool souffle::ExpandFilterTransformer::transform (RamTranslationUnit & translationUnit) inline override protected virtual
transform the translation unit / used by apply translationUnit that will be transformed.
flag reporting whether the RAM program has changed
Implements souffle::RamTransformer.
Definition at line 68 of file RamTransforms.h.
References expandFilters(), and souffle::RamTranslationUnit::getProgram().
{
         return expandFilters(*translationUnit.getProgram());
     }
The documentation for this class was generated from the following files:
RamTransforms.h
RamTransforms.cpp