souffle: souffle::MinimiseProgramTransformer Class Reference
souffle::MinimiseProgramTransformer Class Reference
Transformation pass to remove equivalent rules.
#include <AstTransforms.h>
Public Member Functions
std::string getName () const override
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Private Member Functions
bool transform (AstTranslationUnit &translationUnit) override
Detailed Description
Transformation pass to remove equivalent rules.
Definition at line 197 of file AstTransforms.h.
Member Function Documentation
getName()
std::string souffle::MinimiseProgramTransformer::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 199 of file AstTransforms.h.
References souffle::ResolveAliasesTransformer::transform().
{
         return "MinimiseProgramTransformer";
     }
transform()
bool souffle::MinimiseProgramTransformer::transform (AstTranslationUnit & translationUnit) override private virtual
Implements souffle::AstTransformer.
Definition at line 319 of file MinimiseProgramTransformer.cpp.
References souffle::areBijectivelyEquivalent(), souffle::AstTranslationUnit::getProgram(), souffle::AstProgram::getRelations(), and souffle::AstProgram::removeClause().
{
     AstProgram& program = *translationUnit.getProgram();
     std::vector<AstClause*> clausesToDelete;
     // split up each relation's rules into equivalene classes
     // TODO (azreika): consider turning this into an ast analysis instead
     for (AstRelation* rel : program.getRelations()) {
         std::vector<std::vector<AstClause*>> equivalenceClasses;
         for (AstClause* clause : rel->getClauses()) {
             bool added = false;
             for (std::vector<AstClause*>& eqClass : equivalenceClasses) {
                 AstClause* rep = eqClass[0];
                 if (areBijectivelyEquivalent(rep, clause)) {
                     // clause belongs to an existing equivalence class, so delete it
                     eqClass.push_back(clause);
                     clausesToDelete.push_back(clause);
                     added = true;
                     break;
                 }
             }
             if (!added) {
                 // clause does not belong to any existing equivalence class, so keep it
                 std::vector<AstClause*> clauseToAdd = {clause};
                 equivalenceClasses.push_back(clauseToAdd);
             }
         }
     }
     // remove non-representative clauses
     for (auto clause : clausesToDelete) {
         program.removeClause(clause);
     }
     // changed iff any clauses were deleted
     return !clausesToDelete.empty();
 }
The documentation for this class was generated from the following files:
AstTransforms.h
MinimiseProgramTransformer.cpp