souffle: souffle::InterpreterProgInterface Class Reference
souffle::InterpreterProgInterface Class Reference
Implementation of SouffleProgram interface for an interpreter instance.
#include <InterpreterProgInterface.h>
Public Member Functions
void dumpInputs (std::ostream &) override
Dump inputs: not implemented.
void dumpOutputs (std::ostream &) override
Dump outputs: not implemented.
void executeSubroutine (std::string name, const std::vector< RamDomain > &args, std::vector< RamDomain > &ret, std::vector< bool > &err) override
Run subroutine.
SymbolTable & getSymbolTable () override
Get symbol table.
InterpreterProgInterface (InterpreterEngine &interp)
void loadAll (std::string) override
Load input data: not implemented.
void printAll (std::string) override
Print output data: not implemented.
void run (size_t) override
Run program instance: not implemented.
void runAll (std::string, std::string, size_t) override
Load data, run program instance, store data: not implemented.
~InterpreterProgInterface () override
Public Member Functions inherited from souffle::SouffleProgram
template<typename... Args>
bool contains (const std::tuple< Args... > &t, Relation *relation)
Contains function with std::tuple as input (wrapper)
std::vector< Relation * > getAllRelations () const
Getter of allRelations, which this vector structure contains all relations.
std::vector< Relation * > getInputRelations () const
Getter of inputRelations, which this vector structure contains all input relations.
std::vector< Relation * > getInternalRelations () const
Getter of internalRelations, which this vector structure contains all relations that are neither an input relation or an output relation.
std::size_t getNumThreads ()
Get the number of threads to be used.
std::vector< Relation * > getOutputRelations () const
Getter of outputRelations, which this vector structure contains all output relations.
Relation * getRelation (const std::string &name) const
Get Relation by its name from relationMap, if relation not found, return a nullptr.
std::string getRelationName (const std::string &name) const
Return the name of the target relation from relationMap.
std::size_t getRelationSize (const std::string &name) const
Return the size of the target relation from relationMap.
template<typename... Args>
void insert (const std::tuple< Args... > &t, Relation *relation)
Insert function with std::tuple as input (wrapper)
void purgeInputRelations ()
Remove all the tuples from the inputRelations, calling the purge method of each.
void purgeInternalRelations ()
Remove all the tuples from the internalRelations, calling the purge method of each.
void purgeOutputRelations ()
Remove all the tuples from the outputRelations, calling the purge method of each.
void setNumThreads (std::size_t numThreads)
Set the number of threads to be used.
virtual ~SouffleProgram ()=default
Destructor.
Private Attributes
InterpreterEngine & exec
std::vector< InterpreterRelInterface * > interfaces
const RamProgram & prog
SymbolTable & symTable
Additional Inherited Members
Protected Member Functions inherited from souffle::SouffleProgram
void addRelation (const std::string &name, Relation *rel, bool isInput, bool isOutput)
Add the relation to relationMap (with its name) and allRelations, depends on the properties of the relation, if the relation is an input relation, it will be added to inputRelations, else if the relation is an output relation, it will be added to outputRelations, otherwise will add to internalRelations.
Detailed Description
Implementation of SouffleProgram interface for an interpreter instance.
Definition at line 181 of file InterpreterProgInterface.h.
Constructor & Destructor Documentation
InterpreterProgInterface()
souffle::InterpreterProgInterface::InterpreterProgInterface (InterpreterEngine & interp) inline
Definition at line 183 of file InterpreterProgInterface.h.
References souffle::InterpreterRelInterface::attrNames, souffle::RamRelation::getArg(), souffle::RamRelation::getArgTypeQualifier(), souffle::RamRelation::getArity(), souffle::RamRelation::getName(), souffle::RamRelationStatement::getRelation(), i, n, souffle::InterpreterRelInterface::name, souffle::InterpreterRelInterface::types, and souffle::visitDepthFirst().
             : prog(*interp.getTranslationUnit().getProgram()), exec(interp),
               symTable(interp.getTranslationUnit().getSymbolTable()) {
         uint32_t id = 0;
         // Retrieve AST Relations and store them in a map
         std::map<std::string, const RamRelation*> map;
         visitDepthFirst(prog, [&](const RamRelation& rel) { map[rel.getName()] = &rel; });
         // Build wrapper relations for Souffle's interface
         for (auto& relPtr : exec.getRelationMap()) {
             if (relPtr == nullptr) {
                 // Skip droped relation.
                 continue;
             }
             auto& name = relPtr->getName();
             auto& interpreterRel = *relPtr;
             assert(map[name]);
             const RamRelation& rel = *map[name];
             // construct types and names vectors
             std::vector<std::string> types;
             std::vector<std::string> attrNames;
             for (size_t i = 0; i < rel.getArity(); i++) {
                 std::string t = rel.getArgTypeQualifier(i);
                 types.push_back(t);
                 std::string n = rel.getArg(i);
                 attrNames.push_back(n);
             }
             auto* interface = new InterpreterRelInterface(
                     interpreterRel, symTable, rel.getName(), types, attrNames, id);
             interfaces.push_back(interface);
             bool input;
             bool output;
             visitDepthFirst(prog, [&](const RamStore& store) {
                 if (store.getRelation() == rel) {
                     output = true;
                 }
             });
             visitDepthFirst(prog, [&](const RamLoad& load) {
                 if (load.getRelation() == rel) {
                     input = true;
                 }
             });
             addRelation(rel.getName(), interface, input, output);
             id++;
         }
     }
~InterpreterProgInterface()
souffle::InterpreterProgInterface::~InterpreterProgInterface () inline override
Definition at line 232 of file InterpreterProgInterface.h.
{
         for (auto* interface : interfaces) {
             delete interface;
         }
     }
Member Function Documentation
dumpInputs()
void souffle::InterpreterProgInterface::dumpInputs (std::ostream &) inline override virtual
Dump inputs: not implemented.
Implements souffle::SouffleProgram.
Definition at line 251 of file InterpreterProgInterface.h.
 {}
dumpOutputs()
void souffle::InterpreterProgInterface::dumpOutputs (std::ostream &) inline override virtual
Dump outputs: not implemented.
Implements souffle::SouffleProgram.
Definition at line 254 of file InterpreterProgInterface.h.
 {}
executeSubroutine()
void souffle::InterpreterProgInterface::executeSubroutine (std::string name, const std::vector< RamDomain > & args, std::vector< RamDomain > & ret, std::vector< bool > & err) inline override virtual
Run subroutine.
Reimplemented from souffle::SouffleProgram.
Definition at line 257 of file InterpreterProgInterface.h.
{
         exec.executeSubroutine(name, args, ret, err);
     }
getSymbolTable()
SymbolTable& souffle::InterpreterProgInterface::getSymbolTable () inline override virtual
Get symbol table.
Implements souffle::SouffleProgram.
Definition at line 263 of file InterpreterProgInterface.h.
References souffle::InterpreterRelInterface::symTable.
{
         return symTable;
     }
loadAll()
void souffle::InterpreterProgInterface::loadAll (std::string) inline override virtual
Load input data: not implemented.
Implements souffle::SouffleProgram.
Definition at line 245 of file InterpreterProgInterface.h.
 {}
printAll()
void souffle::InterpreterProgInterface::printAll (std::string) inline override virtual
Print output data: not implemented.
Implements souffle::SouffleProgram.
Definition at line 248 of file InterpreterProgInterface.h.
 {}
run()
void souffle::InterpreterProgInterface::run (size_t) inline override virtual
Run program instance: not implemented.
Reimplemented from souffle::SouffleProgram.
Definition at line 239 of file InterpreterProgInterface.h.
 {}
runAll()
void souffle::InterpreterProgInterface::runAll (std::string , std::string , size_t) inline override virtual
Load data, run program instance, store data: not implemented.
Implements souffle::SouffleProgram.
Definition at line 242 of file InterpreterProgInterface.h.
 {}
Field Documentation
exec
InterpreterEngine& souffle::InterpreterProgInterface::exec private
Definition at line 269 of file InterpreterProgInterface.h.
interfaces
std::vector<InterpreterRelInterface*> souffle::InterpreterProgInterface::interfaces private
Definition at line 271 of file InterpreterProgInterface.h.
prog
const RamProgram& souffle::InterpreterProgInterface::prog private
Definition at line 268 of file InterpreterProgInterface.h.
symTable
SymbolTable& souffle::InterpreterProgInterface::symTable private
Definition at line 270 of file InterpreterProgInterface.h.
The documentation for this class was generated from the following file:
InterpreterProgInterface.h