souffle: souffle::AstConstraint Class Reference
souffle::AstConstraint Class Reference abstract
Subclass of Literal that represents a logical constraint.
#include <AstLiteral.h>
Public Member Functions
AstConstraint * clone () const override=0
Creates a clone of this AST sub-structure.
const AstAtom * getAtom () const override
Obtains the atom referenced by this literal - if any.
virtual void negate ()=0
Negates the constraint.
~AstConstraint () override=default
Public Member Functions inherited from souffle::AstLiteral
AstLiteral ()=default
~AstLiteral () override=default
Public Member Functions inherited from souffle::AstNode
virtual void apply (const AstNodeMapper &mapper)=0
Apply the mapper to all child nodes.
std::string extloc () const
Return source location of the syntactic element.
virtual std::vector< const AstNode * > getChildNodes () const =0
Obtain a list of all embedded AST child nodes.
SrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
virtual void print (std::ostream &os) const =0
Output to a given output stream.
void setSrcLoc (const SrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Additional Inherited Members
Protected Member Functions inherited from souffle::AstNode
virtual bool equal (const AstNode &other) const =0
Abstract equality check for two AST nodes.
Detailed Description
Subclass of Literal that represents a logical constraint.
Definition at line 286 of file AstLiteral.h.
Constructor & Destructor Documentation
~AstConstraint()
souffle::AstConstraint::~AstConstraint () override default
Member Function Documentation
clone()
AstConstraint* souffle::AstConstraint::clone () const override pure virtual
Creates a clone of this AST sub-structure.
Implements souffle::AstLiteral.
Implemented in souffle::AstBinaryConstraint, and souffle::AstBooleanConstraint.
Referenced by souffle::negateLiteral().
getAtom()
const AstAtom* souffle::AstConstraint::getAtom () const inline override virtual
Obtains the atom referenced by this literal - if any.
Implements souffle::AstLiteral.
Definition at line 290 of file AstLiteral.h.
References souffle::AstLiteral::clone().
{
         // This kind of literal has no nested atom
         return nullptr;
     }
negate()
virtual void souffle::AstConstraint::negate () pure virtual
Negates the constraint.
Implemented in souffle::AstBinaryConstraint, and souffle::AstBooleanConstraint.
Referenced by souffle::negateLiteral().
The documentation for this class was generated from the following file:
AstLiteral.h