souffle: souffle::ram::index_utils::TrieIndex< Index > Class Template Reference
souffle::ram::index_utils::TrieIndex< Index > Class Template Reference
A trie index is like a direct index storing the indexed elements directly within the maintained index structure.
#include <CompiledIndexUtils.h>
Data Structures
class iterator
Public Types
using operation_hints = typename tree_type::op_context
Public Member Functions
iterator begin () const
void clear ()
bool contains (const tuple_type &tuple, operation_hints &ctxt) const
bool empty () const
iterator end () const
template<typename SubIndex >
range< iterator > equalRange (const tuple_type &tuple, operation_hints &ctxt) const
iterator find (const tuple_type &key, operation_hints &ctxt) const
bool insert (const tuple_type &tuple, operation_hints &ctxt)
void insertAll (const TrieIndex &other)
std::vector< range< iterator > > partition () const
void printHintStatistics (std::ostream &out, const std::string &prefix) const
std::size_t size () const
Static Public Member Functions
static void printDescription (std::ostream &out)
Private Types
using tree_type = Trie< Index::size >
using tuple_type = typename tree_type::entry_type
Static Private Member Functions
static tuple_type orderIn (const tuple_type &tuple)
static tuple_type orderOut (const tuple_type &tuple)
Private Attributes
tree_type data
Detailed Description
template<typename Index>
class souffle::ram::index_utils::TrieIndex< Index >
A trie index is like a direct index storing the indexed elements directly within the maintained index structure.
However, unlike the B-Tree utilized by a direct index, a Trie is utilized.
Template Parameters
Index .. the index to be internally utilized.
Definition at line 850 of file CompiledIndexUtils.h.
Member Typedef Documentation
operation_hints
template<typename Index > using souffle::ram::index_utils::TrieIndex< Index >::operation_hints = typename tree_type::op_context
Definition at line 858 of file CompiledIndexUtils.h.
tree_type
template<typename Index > using souffle::ram::index_utils::TrieIndex< Index >::tree_type = Trie<Index::size> private
Definition at line 851 of file CompiledIndexUtils.h.
tuple_type
template<typename Index > using souffle::ram::index_utils::TrieIndex< Index >::tuple_type = typename tree_type::entry_type private
Definition at line 853 of file CompiledIndexUtils.h.
Member Function Documentation
begin()
template<typename Index > iterator souffle::ram::index_utils::TrieIndex< Index >::begin () const inline
Definition at line 940 of file CompiledIndexUtils.h.
References souffle::Trie< Dim >::begin().
{
         return iterator(data.begin());
     }
clear()
template<typename Index > void souffle::ram::index_utils::TrieIndex< Index >::clear () inline
Definition at line 882 of file CompiledIndexUtils.h.
References souffle::Trie< Dim >::clear().
                  {
         data.clear();
     }
contains()
template<typename Index > bool souffle::ram::index_utils::TrieIndex< Index >::contains (const tuple_type & tuple, operation_hints & ctxt) const inline
Definition at line 868 of file CompiledIndexUtils.h.
References souffle::Trie< Dim >::contains().
{
         return data.contains(orderIn(tuple), ctxt);
     }
empty()
template<typename Index > bool souffle::ram::index_utils::TrieIndex< Index >::empty () const inline
Definition at line 860 of file CompiledIndexUtils.h.
References souffle::Trie< Dim >::empty().
{
         return data.empty();
     }
end()
template<typename Index > iterator souffle::ram::index_utils::TrieIndex< Index >::end () const inline
Definition at line 944 of file CompiledIndexUtils.h.
References souffle::Trie< Dim >::end().
{
         return iterator(data.end());
     }
equalRange()
template<typename Index > template<typename SubIndex > range<iterator> souffle::ram::index_utils::TrieIndex< Index >::equalRange (const tuple_type & tuple, operation_hints & ctxt) const inline
Definition at line 962 of file CompiledIndexUtils.h.
References souffle::make_range().
{
         static_assert(is_compatible_with<SubIndex, Index>::value, "Invalid sub-index query!");
         auto r = data.template getBoundaries<SubIndex::size>(orderIn(tuple), ctxt);
         return make_range(iterator(r.begin()), iterator(r.end()));
     }
find()
template<typename Index > iterator souffle::ram::index_utils::TrieIndex< Index >::find (const tuple_type & key, operation_hints & ctxt) const inline
Definition at line 957 of file CompiledIndexUtils.h.
References souffle::Trie< Dim >::find().
{
         return iterator(data.find(orderIn(key), ctxt));
     }
insert()
template<typename Index > bool souffle::ram::index_utils::TrieIndex< Index >::insert (const tuple_type & tuple, operation_hints & ctxt) inline
Definition at line 872 of file CompiledIndexUtils.h.
References souffle::Trie< Dim >::insert().
{
         // the Trie-insert is synchronized internally
         return data.insert(orderIn(tuple), ctxt);
     }
insertAll()
template<typename Index > void souffle::ram::index_utils::TrieIndex< Index >::insertAll (const TrieIndex< Index > & other) inline
Definition at line 877 of file CompiledIndexUtils.h.
References souffle::ram::index_utils::TrieIndex< Index >::data, and souffle::Trie< Dim >::insertAll().
{
         // use trie merge
         data.insertAll(other.data);
     }
orderIn()
template<typename Index > static tuple_type souffle::ram::index_utils::TrieIndex< Index >::orderIn (const tuple_type & tuple) inline static private
Definition at line 986 of file CompiledIndexUtils.h.
{
         tuple_type res;
         order<Index>().order_in(res, tuple);
         return res;
     }
orderOut()
template<typename Index > static tuple_type souffle::ram::index_utils::TrieIndex< Index >::orderOut (const tuple_type & tuple) inline static private
Definition at line 992 of file CompiledIndexUtils.h.
{
         tuple_type res;
         order<Index>().order_out(res, tuple);
         return res;
     }
partition()
template<typename Index > std::vector<range<iterator> > souffle::ram::index_utils::TrieIndex< Index >::partition () const inline
Definition at line 948 of file CompiledIndexUtils.h.
References souffle::make_range(), and souffle::Trie< Dim >::partition().
{
         // wrap partitions up in re-order iterators
         std::vector<range<iterator>> res;
         for (const auto& cur : data.partition(10000)) {
             res.push_back(make_range(iterator(cur.begin()), iterator(cur.end())));
         }
         return res;
     }
printDescription()
template<typename Index > static void souffle::ram::index_utils::TrieIndex< Index >::printDescription (std::ostream & out) inline static
Definition at line 968 of file CompiledIndexUtils.h.
{
         out << "trie-index(" << Index() << ")";
     }
printHintStatistics()
template<typename Index > void souffle::ram::index_utils::TrieIndex< Index >::printHintStatistics (std::ostream & out, const std::string & prefix) const inline
Definition at line 972 of file CompiledIndexUtils.h.
References souffle::detail::TrieBase< Dim, Derived >::getHintStatistics().
{
         const auto& stats = data.getHintStatistics();
         out << prefix << "Trie-Index: (Hits/Misses/Total)\n";
         out << prefix << "      Insert: " << stats.inserts.getHits() << "/" << stats.inserts.getMisses()
             << "/" << stats.inserts.getAccesses() << "\n";
         out << prefix << "    Contains: " << stats.contains.getHits() << "/" << stats.contains.getMisses()
             << "/" << stats.contains.getAccesses() << "\n";
         out << prefix << "  RangeQuery: " << stats.get_boundaries.getHits() << "/"
             << stats.get_boundaries.getMisses() << "/" << stats.get_boundaries.getAccesses() << "\n";
     }
size()
template<typename Index > std::size_t souffle::ram::index_utils::TrieIndex< Index >::size () const inline
Definition at line 864 of file CompiledIndexUtils.h.
References souffle::Trie< Dim >::size().
{
         return data.size();
     }
Field Documentation
data
template<typename Index > tree_type souffle::ram::index_utils::TrieIndex< Index >::data private
Definition at line 855 of file CompiledIndexUtils.h.
Referenced by souffle::ram::index_utils::TrieIndex< Index >::insertAll().
The documentation for this class was generated from the following file:
CompiledIndexUtils.h