souffle: souffle::RamStratum Class Reference
souffle::RamStratum Class Reference
Stratum statement.
#include <RamStatement.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
RamStratum * clone () const override
Create a clone (i.e.
const RamStatement & getBody () const
Get stratum body.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
const int getIndex () const
Get stratum index.
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
RamStratum (std::unique_ptr< RamStatement > b, const int i)
Public Member Functions inherited from souffle::RamStatement
void print (std::ostream &os) const override
Print RAM node.
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, std::unique_ptr< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Attributes
std::unique_ptr< RamStatement > body
Body of stratum.
const int index
Stratum number.
Detailed Description
Stratum statement.
Wrap strata of program, corresponding to an iteration in the semi-naive evaluation
The following example denotes the execution of stratum 0:
BEGIN_STRATUM 0
  ...
END_STRATUM 0
Definition at line 952 of file RamStatement.h.
Constructor & Destructor Documentation
RamStratum()
souffle::RamStratum::RamStratum (std::unique_ptr< RamStatement > b, const int i) inline
Definition at line 954 of file RamStatement.h.
 : body(std::move(b)), index(i) {}
Member Function Documentation
apply()
void souffle::RamStratum::apply (const RamNodeMapper & mapper) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::RamNode.
Definition at line 983 of file RamStatement.h.
{
         body = map(std::move(body));
     }
clone()
RamStratum* souffle::RamStratum::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamStatement.
Definition at line 979 of file RamStatement.h.
{
         return new RamStratum(std::unique_ptr<RamStatement>(body->clone()), index);
     }
equal()
bool souffle::RamStratum::equal (const RamNode & other) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamNode.
Definition at line 994 of file RamStatement.h.
References getBody().
{
         assert(nullptr != dynamic_cast<const RamStratum*>(&node));
         const auto& other = static_cast<const RamStratum&>(node);
         return getBody() == other.getBody() && getIndex() == other.getIndex();
     }
getBody()
const RamStatement& souffle::RamStratum::getBody () const inline
Get stratum body.
Definition at line 957 of file RamStatement.h.
Referenced by equal(), souffle::Synthesiser::generateCode(), and souffle::NodeGenerator::visitStratum().
{
         assert(body != nullptr && "Body of stratum is a null-pointer");
         return *body;
     }
getChildNodes()
std::vector<const RamNode*> souffle::RamStratum::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::RamNode.
Definition at line 975 of file RamStatement.h.
{
         return {body.get()};
     }
getIndex()
const int souffle::RamStratum::getIndex () const inline
Get stratum index.
Definition at line 963 of file RamStatement.h.
Referenced by souffle::Synthesiser::generateCode().
{
         return index;
     }
print()
void souffle::RamStratum::print (std::ostream & os, int tabpos) const inline override virtual
Pretty print with indentation.
Implements souffle::RamStatement.
Definition at line 967 of file RamStatement.h.
References souffle::times().
{
         os << times(" ", tabpos);
         os << "BEGIN_STRATUM " << index << std::endl;
         body->print(os, tabpos + 1);
         os << times(" ", tabpos);
         os << "END_STRATUM " << index << std::endl;
     }
Field Documentation
body
std::unique_ptr<RamStatement> souffle::RamStratum::body protected
Body of stratum.
Definition at line 989 of file RamStatement.h.
index
const int souffle::RamStratum::index protected
Stratum number.
Definition at line 992 of file RamStatement.h.
The documentation for this class was generated from the following file:
RamStatement.h