souffle: souffle::ram::index_utils::IndirectIndex< Tuple, Index > Struct Template Reference
souffle::ram::index_utils::IndirectIndex< Tuple, Index > Struct Template Reference
A wrapper realizing indirect indices – by storing pointers to the actually indexed values.
#include <CompiledIndexUtils.h>
Public Types
using data_structure = typename std::conditional<(int)(Tuple::arity)==(int)(Index::size), btree_set< const Tuple *, index_utils::deref_compare< typename Index::comparator > >, btree_multiset< const Tuple *, index_utils::deref_compare< typename Index::comparator > >>::type
using iterator = IterDerefWrapper< typename data_structure::const_iterator >
using key_type = typename std::remove_cv< typename std::remove_pointer< typename data_structure::key_type >::type >::type
using operation_hints = typename data_structure::operation_hints
Public Member Functions
iterator begin () const
void clear ()
bool contains (const key_type &key, operation_hints &hints) const
bool empty () const
iterator end () const
template<typename SubIndex >
range< iterator > equalRange (const key_type &key, operation_hints &hints) const
iterator find (const key_type &key, operation_hints &hints) const
bool insert (const key_type &key, operation_hints &hints)
void insertAll (const IndirectIndex &other)
std::vector< range< iterator > > partition () const
Return a list of iterators, s.t.
void printHintStatistics (std::ostream &out, const std::string &prefix) const
std::size_t size () const
Static Public Member Functions
static void printDescription (std::ostream &out)
Private Attributes
data_structure index
Detailed Description
template<typename Tuple, typename Index>
struct souffle::ram::index_utils::IndirectIndex< Tuple, Index >
A wrapper realizing indirect indices – by storing pointers to the actually indexed values.
Template Parameters
Tuple .. the type of tuple to be maintained by this index
Index .. the index to be internally utilized.
Definition at line 686 of file CompiledIndexUtils.h.
Member Typedef Documentation
data_structure
template<typename Tuple , typename Index > using souffle::ram::index_utils::IndirectIndex< Tuple, Index >::data_structure = typename std::conditional<(int)(Tuple::arity) == (int)(Index::size), btree_set<const Tuple*, index_utils::deref_compare<typename Index::comparator> >, btree_multiset<const Tuple*, index_utils::deref_compare<typename Index::comparator> >>::type
Definition at line 689 of file CompiledIndexUtils.h.
iterator
template<typename Tuple , typename Index > using souffle::ram::index_utils::IndirectIndex< Tuple, Index >::iterator = IterDerefWrapper<typename data_structure::const_iterator>
Definition at line 694 of file CompiledIndexUtils.h.
key_type
template<typename Tuple , typename Index > using souffle::ram::index_utils::IndirectIndex< Tuple, Index >::key_type = typename std::remove_cv< typename std::remove_pointer<typename data_structure::key_type>::type>::type
Definition at line 692 of file CompiledIndexUtils.h.
operation_hints
template<typename Tuple , typename Index > using souffle::ram::index_utils::IndirectIndex< Tuple, Index >::operation_hints = typename data_structure::operation_hints
Definition at line 696 of file CompiledIndexUtils.h.
Member Function Documentation
begin()
template<typename Tuple , typename Index > iterator souffle::ram::index_utils::IndirectIndex< Tuple, Index >::begin () const inline
Definition at line 750 of file CompiledIndexUtils.h.
{
         return index.begin();
     }
clear()
template<typename Tuple , typename Index > void souffle::ram::index_utils::IndirectIndex< Tuple, Index >::clear () inline
Definition at line 758 of file CompiledIndexUtils.h.
                  {
         index.clear();
     }
contains()
template<typename Tuple , typename Index > bool souffle::ram::index_utils::IndirectIndex< Tuple, Index >::contains (const key_type & key, operation_hints & hints) const inline
Definition at line 721 of file CompiledIndexUtils.h.
{
         return index.contains(&key, hints);
     }
empty()
template<typename Tuple , typename Index > bool souffle::ram::index_utils::IndirectIndex< Tuple, Index >::empty () const inline
Definition at line 703 of file CompiledIndexUtils.h.
{
         return index.empty();
     }
end()
template<typename Tuple , typename Index > iterator souffle::ram::index_utils::IndirectIndex< Tuple, Index >::end () const inline
Definition at line 754 of file CompiledIndexUtils.h.
{
         return index.end();
     }
equalRange()
template<typename Tuple , typename Index > template<typename SubIndex > range<iterator> souffle::ram::index_utils::IndirectIndex< Tuple, Index >::equalRange (const key_type & key, operation_hints & hints) const inline
Definition at line 730 of file CompiledIndexUtils.h.
References arity, souffle::derefIter(), low, and souffle::make_range().
{
         // more efficient support for full-indices
         if (int(SubIndex::size) == int(Index::size) && int(Index::size) == int(key_type::arity)) {
             // in this case there is at most one element with this value
             auto pos = find(key, hints);
             auto end = this->end();
             if (pos != end) {
                 end = pos;
                 ++end;
             }
             return make_range(pos, end);
         }
         // compute lower and upper bounds
         auto low = lower<Index, SubIndex>(key);
         auto hig = raise<Index, SubIndex>(key);
         return make_range(
                 derefIter(index.lower_bound(&low, hints)), derefIter(index.upper_bound(&hig, hints)));
     }
find()
template<typename Tuple , typename Index > iterator souffle::ram::index_utils::IndirectIndex< Tuple, Index >::find (const key_type & key, operation_hints & hints) const inline
Definition at line 725 of file CompiledIndexUtils.h.
{
         return index.find(&key, hints);
     }
insert()
template<typename Tuple , typename Index > bool souffle::ram::index_utils::IndirectIndex< Tuple, Index >::insert (const key_type & key, operation_hints & hints) inline
Definition at line 711 of file CompiledIndexUtils.h.
{
         // insert the element (insert is synchronized internally)
         return index.insert(&key, hints);
     }
insertAll()
template<typename Tuple , typename Index > void souffle::ram::index_utils::IndirectIndex< Tuple, Index >::insertAll (const IndirectIndex< Tuple, Index > & other) inline
Definition at line 716 of file CompiledIndexUtils.h.
References souffle::ram::index_utils::IndirectIndex< Tuple, Index >::index.
{
         // use index's insert-all
         index.insertAll(other.index);
     }
partition()
template<typename Tuple , typename Index > std::vector<range<iterator> > souffle::ram::index_utils::IndirectIndex< Tuple, Index >::partition () const inline
Return a list of iterators, s.t.
we can process in parallel. "an approximation of the number of sub-ranges to be included in the resulting partition." "The numbers there [400] are not very important, as long as they are large enough (~10x the number of maximum expected cores) and not too large, such that processing a fragment lasts less than e.g. 1ms."
Parameters
np the number of iterators to attempt to return, which represents slices of the data structure
Returns
a vector of these iterator ranges
Definition at line 771 of file CompiledIndexUtils.h.
References souffle::derefIter(), and souffle::make_range().
{
         std::vector<range<iterator>> res;
         for (const auto& cur : index.getChunks(400)) {
             res.push_back(make_range(derefIter(cur.begin()), derefIter(cur.end())));
         }
         return res;
     }
printDescription()
template<typename Tuple , typename Index > static void souffle::ram::index_utils::IndirectIndex< Tuple, Index >::printDescription (std::ostream & out) inline static
Definition at line 779 of file CompiledIndexUtils.h.
{
         out << "indirect-btree-index(" << Index() << ")";
     }
printHintStatistics()
template<typename Tuple , typename Index > void souffle::ram::index_utils::IndirectIndex< Tuple, Index >::printHintStatistics (std::ostream & out, const std::string & prefix) const inline
Definition at line 783 of file CompiledIndexUtils.h.
{
         const auto& stats = index.getHintStatistics();
         out << prefix << "Indirect B-Tree Index: (Hits/Misses/Total)\n";
         out << prefix << "       Insert: " << stats.inserts.getHits() << "/" << stats.inserts.getMisses()
             << "/" << stats.inserts.getAccesses() << "\n";
         out << prefix << "     Contains: " << stats.contains.getHits() << "/" << stats.contains.getMisses()
             << "/" << stats.contains.getAccesses() << "\n";
         out << prefix << "  lower bound: " << stats.lower_bound.getHits() << "/"
             << stats.lower_bound.getMisses() << "/" << stats.lower_bound.getAccesses() << "\n";
         out << prefix << "  upper bound: " << stats.upper_bound.getHits() << "/"
             << stats.upper_bound.getMisses() << "/" << stats.upper_bound.getAccesses() << "\n";
     }
size()
template<typename Tuple , typename Index > std::size_t souffle::ram::index_utils::IndirectIndex< Tuple, Index >::size () const inline
Definition at line 707 of file CompiledIndexUtils.h.
{
         return index.size();
     }
Field Documentation
index
template<typename Tuple , typename Index > data_structure souffle::ram::index_utils::IndirectIndex< Tuple, Index >::index private
Definition at line 700 of file CompiledIndexUtils.h.
Referenced by souffle::ram::index_utils::IndirectIndex< Tuple, Index >::insertAll().
The documentation for this struct was generated from the following file:
CompiledIndexUtils.h